// frontend/src/features/student/pages/engage-page.component.ts
import { Component } from "@angular/core";
import { PhasePageComponent } from "../../ova_workspace/pages/phase-page.component";

@Component({
  selector: "gn-engage-page",
  standalone: true,
  imports: [PhasePageComponent],
  template: `
    <gn-phase-page
      phase="ENGAGE"
      emoji="🎯"
      description="Selecciona un tipo de recurso, escribe el concepto de ML y genera el material con IA real."
    ></gn-phase-page>
  `,
})
export class EngagePageComponent {}

// frontend-react-legacy/src/features/student/pages/EngagePage.tsx
import { PhasePage } from '@/features/ova_workspace/pages/PhasePage'
import {
  fetchPhaseRecursos,
  generatePhaseResource,
} from '@/features/ova_workspace/services/phases/phaseService'

export function EngagePage() {
  return (
    <PhasePage
      phase="ENGAGE"
      emoji="🎯"
      description="Selecciona un tipo de recurso, escribe el concepto de ML y genera el material con IA real."
      fetchRecursos={() => fetchPhaseRecursos('engage')}
      generateResource={(
        resourceType: string | number,
        concept: string,
        uploadIds?: string[],
      ) => generatePhaseResource('engage', resourceType, concept, uploadIds)}
    />
  )
}
