// frontend/src/features/student/pages/explore-page.component.ts
import { Component } from "@angular/core";
import { PhasePageComponent } from "../../ova_workspace/pages/phase-page.component";

@Component({
  selector: "gn-explore-page",
  standalone: true,
  imports: [PhasePageComponent],
  template: `
    <gn-phase-page
      phase="EXPLORE"
      emoji="🔍"
      description="Interactúa con simuladores y laboratorios para construir tus propias hipótesis antes de ver la teoría formal."
    ></gn-phase-page>
  `,
})
export class ExplorePageComponent {}

// frontend-react-legacy/src/features/student/pages/ExplorePage.tsx
import { PhasePage } from '@/features/ova_workspace/pages/PhasePage'
import {
  fetchPhaseRecursos,
  generatePhaseResource,
} from '@/features/ova_workspace/services/phases/phaseService'

export function ExplorePage() {
  return (
    <PhasePage
      phase="EXPLORE"
      emoji="🔍"
      description="Interactúa con simuladores y laboratorios para construir tus propias hipótesis antes de ver la teoría formal."
      fetchRecursos={() => fetchPhaseRecursos('explore')}
      generateResource={(
        resourceType: string | number,
        concept: string,
        uploadIds?: string[],
      ) => generatePhaseResource('explore', resourceType, concept, uploadIds)}
    />
  )
}
