// frontend/src/app/layout/components/navbar-brand.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "gn-navbar-brand",
  standalone: true,
  imports: [RouterLink],
  template: `
    <a
      routerLink="/dashboard"
      class="font-display text-xl font-semibold tracking-tight text-foreground"
    >
      Gen<span class="text-primary">OVA</span>
      <span
        class="ml-1.5 align-middle text-[10px] font-sans font-semibold uppercase tracking-[0.18em] text-accent-brand"
      >
        ML
      </span>
    </a>
  `,
})
export class NavbarBrandComponent {}

// frontend-react-legacy/src/core/layouts/components/NavbarBrand.tsx
import { Link } from 'react-router'

export function NavbarBrand() {
  return (
    <Link
      to="/dashboard"
      className="font-display text-xl font-semibold tracking-tight text-foreground"
    >
      Gen<span className="text-primary">OVA</span>
      <span className="ml-1.5 align-middle text-[10px] font-sans font-semibold uppercase tracking-[0.18em] text-accent-brand">
        ML
      </span>
    </Link>
  )
}
