// frontend-react-legacy/src/features/ova_library/components/modals/EditMetadataModal.tsx
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm, useWatch } from 'react-hook-form'
import { Button } from '@/core/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/core/components/ui/dialog'
import { Input } from '@/core/components/ui/input'
import { Label } from '@/core/components/ui/label'
import { Textarea } from '@/core/components/ui/textarea'
import {
  type MetadataInput,
  metadataSchema,
} from '@/features/ova_library/lib/metadataSchema'

interface EditMetadataModalProps {
  initial: { title: string; description?: string }
  onSave: (values: MetadataInput) => Promise<boolean>
  onCancel: () => void
  isLoading: boolean
}

export function EditMetadataModal({
  initial,
  onSave,
  onCancel,
  isLoading,
}: EditMetadataModalProps) {
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm<MetadataInput>({
    resolver: zodResolver(metadataSchema),
    defaultValues: {
      title: initial?.title || '',
      description: initial?.description || '',
    },
  })
  const title = useWatch({ control, name: 'title' }) || ''

  return (
    <Dialog
      open={true}
      onOpenChange={(open) => {
        if (!open) onCancel()
      }}
    >
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Editar metadatos</DialogTitle>
        </DialogHeader>
        <p className="text-xs text-muted-foreground -mt-2">
          Actualiza el título y descripción del OVA.
        </p>

        <form onSubmit={handleSubmit(onSave)} className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="metadata-title">Título *</Label>
            <Input
              id="metadata-title"
              type="text"
              maxLength={250}
              placeholder="Ej. Regresión lineal aplicada"
              aria-invalid={!!errors.title}
              {...register('title')}
            />
            <p className="text-[11px] text-muted-foreground">
              {title.length}/100
            </p>
            {errors.title ? (
              <p className="text-xs font-medium text-destructive">
                {errors.title.message}
              </p>
            ) : null}
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="metadata-description">Descripción</Label>
            <Textarea
              id="metadata-description"
              rows={4}
              className="resize-none"
              placeholder="Opcional"
              {...register('description')}
            />
          </div>

          <div className="flex flex-col-reverse sm:flex-row gap-2 sm:gap-3 pt-2 border-t border-border">
            <Button
              type="button"
              variant="outline"
              className="flex-1"
              onClick={onCancel}
              disabled={isLoading}
            >
              Cancelar
            </Button>
            <Button type="submit" className="flex-1" disabled={isLoading}>
              {isLoading ? 'Guardando...' : 'Guardar'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/features/ova-library/components/modals/edit-metadata-modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  type OnInit,
  output,
  signal,
} from "@angular/core";
import { form, FormField, maxLength, required } from "@angular/forms/signals";
import { HlmInput } from "@spartan-ng/helm/input";

import { ButtonComponent } from "@/core/components/ui/button.component";
import { DialogComponent } from "@/core/components/ui/dialog.component";
import type { MetadataInput } from "@/features/ova-library/lib/metadataSchema";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-edit-metadata-modal",
  imports: [DialogComponent, FormField, ButtonComponent, HlmInput],
  template: `
    <gn-dialog
      [open]="true"
      width="32rem"
      [disableClose]="isLoading()"
      (openChange)="$event || onCancel.emit()"
    >
      <div class="p-6 bg-card">
        <h2 class="text-lg font-semibold tracking-tight">Editar metadatos</h2>
        <p class="text-xs text-muted-foreground mt-1 mb-4">
          Actualiza el título y descripción del OVA.
        </p>

        <form (submit)="onSubmit(); $event.preventDefault()" class="space-y-4">
          <div class="space-y-1.5">
            <label
              for="metadata-title"
              class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Título *
            </label>
            <input
              id="metadata-title"
              type="text"
              hlmInput
              class="w-full"
              placeholder="Ej. Regresión lineal aplicada"
              [formField]="metadataForm.title"
            />
            <p class="text-[11px] text-muted-foreground">{{ titleLength() }}/100</p>
            @if (metadataForm.title().touched() && metadataForm.title().errors().length) {
              <p class="text-xs font-medium text-destructive">
                El título es obligatorio y no puede superar 100 caracteres.
              </p>
            }
          </div>

          <div class="space-y-1.5">
            <label
              for="metadata-description"
              class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Descripción
            </label>
            <textarea
              id="metadata-description"
              rows="4"
              class="w-full flex min-h-[80px] rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 resize-none"
              placeholder="Opcional"
              [formField]="metadataForm.description"
            ></textarea>
          </div>

          <div
            class="flex flex-col-reverse sm:flex-row gap-2 sm:gap-3 pt-4 border-t border-border mt-4"
          >
            <gn-button
              type="button"
              variant="outline"
              class="flex-1"
              (onClick)="onCancel.emit()"
              [disabled]="isLoading()"
            >
              Cancelar
            </gn-button>
            <gn-button
              type="submit"
              class="flex-1"
              [disabled]="isLoading() || metadataForm().invalid()"
              [loading]="isLoading()"
            >
              {{ isLoading() ? "Guardando..." : "Guardar" }}
            </gn-button>
          </div>
        </form>
      </div>
    </gn-dialog>
  `,
})
export class EditMetadataModalComponent implements OnInit {
  readonly initial = input.required<{
    title: string;
    description?: string;
  }>();
  readonly isLoading = input(false);

  readonly onSave = output<MetadataInput>();
  readonly onCancel = output();

  protected readonly metadataModel = signal({ title: "", description: "" });
  protected readonly metadataForm = form(this.metadataModel, (p) => {
    required(p.title, { message: "El título es obligatorio." });
    maxLength(p.title, 100, { message: "El título no puede superar 100 caracteres." });
    maxLength(p.description, 2000, { message: "La descripción no puede superar 2000 caracteres." });
  });

  protected readonly titleLength = computed(() => this.metadataModel().title.length);

  ngOnInit() {
    this.metadataModel.set({
      title: this.initial()?.title || "",
      description: this.initial()?.description || "",
    });
  }

  onSubmit() {
    if (this.metadataForm().valid()) {
      this.onSave.emit(this.metadataModel());
    }
  }
}
