// frontend/src/features/ova-library/components/cards/ova-card.component.ts
import { Component, Input, inject, input, output } from "@angular/core";
import { Router } from "@angular/router";
import { BadgeComponent } from "@/core/components/ui/badge.component";
import { ButtonComponent } from "@/core/components/ui/button.component";
import type { OvaListItem } from "@/features/ova-library/lib/types";
import type { OvaJobInfo } from "@/features/ova-library/lib/job-types";
import { OvaCardShellComponent } from "./ova-card-shell.component";

export type { OvaJobInfo };

@Component({
  selector: "gn-ova-card",
  standalone: true,
  imports: [OvaCardShellComponent, ButtonComponent, BadgeComponent],
  template: `
    <gn-ova-card-shell
      [ova]="ova"
      [isSelected]="isSelected()"
      (onToggleSelect)="onToggleSelect.emit($event)"
      [checkboxDisabled]="isGenerating"
      [dateValue]="formatDate(ova['created_at'])"
    >
      <div extraBadges class="flex gap-1 items-center">
        @if (ova['version_number']) {
          <gn-badge variant="outline" class="text-[10px] text-muted-foreground">
            v{{ ova['version_number'] }}
          </gn-badge>
        }
        @if (isGenerating && job?.progress) {
          <gn-badge variant="outline" class="text-[10px] text-primary border-primary/30">
            {{ job!.progress!.done }}/{{ job!.progress!.total }}
          </gn-badge>
        }
      </div>

      <div footer class="flex flex-col gap-1.5 w-full">
        <!-- Generando: actions -->
        @if (isGenerating) {
          <div class="flex gap-2 mb-1.5">
            @if (job?.isInterrupted) {
              <gn-button
                variant="outline"
                size="sm"
                class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
                (onClick)="handleContinue()"
              >
                <!-- <Play /> -->
                Continuar
              </gn-button>
            }
            @if (!job?.isInterrupted) {
              <gn-button
                variant="outline"
                size="sm"
                class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
                [disabled]="!job?.jobId"
                (onClick)="handleResume()"
              >
                <!-- <Clock /> -->
                Reanudar / Ver progreso
              </gn-button>
            }
          </div>
        }

        <div class="flex items-center gap-1.5 w-full">
          <gn-button
            variant="outline"
            size="sm"
            class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
            [disabled]="isGenerating || isDuplicating()"
            (onClick)="goToWorkspace()"
          >
            <!-- <PencilSimple /> -->
            Editar
          </gn-button>
          <gn-button
            variant="outline"
            size="sm"
            class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
            [disabled]="isGenerating || isDuplicating()"
            (onClick)="onEditMetadata.emit(ova)"
          >
            <!-- <FileText /> -->
            Metadatos
          </gn-button>
        </div>

        <div class="flex flex-wrap items-center gap-1.5 w-full">
          <gn-button
            variant="outline"
            size="sm"
            class="flex-1"
            [disabled]="isGenerating || isDuplicating()"
            (onClick)="onDuplicate.emit(ova.id)"
          >
            <!-- <Copy /> -->
            {{ isDuplicating() ? 'Duplicando...' : 'Duplicar' }}
          </gn-button>
          <gn-button
            variant="outline"
            size="sm"
            class="flex-1"
            [disabled]="!isReady || isDownloading() || isDuplicating()"
            (onClick)="onDownload.emit({ id: ova.id, title: ova.title || '' })"
          >
            <!-- <DownloadSimple /> -->
            {{ isDownloading() ? 'Descargando...' : 'Descargar' }}
          </gn-button>
          <gn-button
            variant="outline"
            size="sm"
            class="flex-1 text-destructive border-destructive/30 hover:bg-destructive/5"
            [disabled]="isGenerating || isMoving() || isDuplicating()"
            (onClick)="onMoveToTrash.emit(ova)"
          >
            <!-- <Trash /> -->
            {{ isMoving() ? 'Moviendo...' : 'Papelera' }}
          </gn-button>
        </div>
      </div>
    </gn-ova-card-shell>
  `,
})
export class OvaCardComponent {
  @Input({ required: true }) ova!: OvaListItem;
  @Input() job?: OvaJobInfo;
  readonly isSelected = input(false);
  readonly isMoving = input(false);
  readonly isDownloading = input(false);
  readonly isDuplicating = input(false);

  readonly onToggleSelect = output<string>();
  readonly onMoveToTrash = output<OvaListItem>();
  readonly onDownload = output<{
    id: string;
    title: string;
  }>();
  readonly onDuplicate = output<string>();
  readonly onEditMetadata = output<OvaListItem>();
  readonly onResume = output<string>();

  private router = inject(Router);

  get isGenerating(): boolean {
    return this.ova.status === "generando";
  }

  get isReady(): boolean {
    return this.ova.status === "listo";
  }

  formatDate(date: unknown): string {
    if (!date) return "";
    return new Date(date as string).toLocaleDateString();
  }

  handleResume() {
    this.router.navigate(["/crear"], { state: { resumeJobId: this.job?.jobId } });
  }

  async handleContinue() {
    this.onResume.emit(this.ova.id);
  }

  goToWorkspace() {
    this.router.navigate([`/workspace/${this.ova.id}`]);
  }
}

// archive/frontend-react-legacy/src/features/ova_library/components/cards/OvaCard.tsx
import {
  Clock,
  Copy,
  DownloadSimple,
  FileText,
  PencilSimple,
  Play,
  Trash,
} from '@phosphor-icons/react'
import { memo } from 'react'
import { useNavigate } from 'react-router'
import { toast } from 'sonner'
import { Badge } from '@/core/components/ui/badge'
import { Button } from '@/core/components/ui/button'
import { formatDate } from '@/features/ova_library/lib/formatDate'
import type { OvaListItem } from '@/features/ova_library/lib/types'
import { OvaCardShell } from './OvaCardShell'

export interface JobInfo {
  jobId?: string | null
  status?: string | null
  progress?: { done: number; total: number } | null
  isInterrupted?: boolean
}

interface OvaCardProps {
  ova: OvaListItem
  job?: JobInfo | Record<string, never>
  onResume: (ovaId: string) => Promise<void>
  isSelected: boolean
  onToggleSelect: (id: string) => void
  onMoveToTrash: (ova: OvaListItem) => void
  onDownload: (ovaId: string, title: string) => Promise<void>
  onDuplicate: (ovaId: string) => void
  onEditMetadata: (ova: OvaListItem) => void
  isMoving: boolean
  isDownloading: boolean
  isDuplicating: boolean
}

const EMPTY_JOB: Record<string, never> = {}

function OvaCardImpl({
  ova,
  job = EMPTY_JOB,
  onResume,
  isSelected,
  onToggleSelect,
  onMoveToTrash,
  onDownload,
  onDuplicate,
  onEditMetadata,
  isMoving,
  isDownloading,
  isDuplicating,
}: OvaCardProps) {
  const navigate = useNavigate()
  const isGenerating = ova.status === 'generando'
  const isReady = ova.status === 'listo'
  const { jobId, progress, isInterrupted } = job as JobInfo

  const handleResume = () => {
    navigate('/crear-ova', { state: { resumeJobId: jobId } })
  }

  const handleContinue = async () => {
    try {
      await onResume(ova.id)
      navigate('/crear-ova', { state: { resumeJobId: jobId } })
    } catch {
      toast.error('No se pudo continuar la generación.')
    }
  }

  const extraBadges = (
    <>
      {ova.version_number ? (
        <Badge variant="outline" className="text-[10px] text-muted-foreground">
          v{ova.version_number as string}
        </Badge>
      ) : null}
      {isGenerating && progress ? (
        <Badge
          variant="outline"
          className="text-[10px] text-primary border-primary/30"
        >
          {progress.done}/{progress.total}
        </Badge>
      ) : null}
    </>
  )

  const footer = (
    <>
      {isGenerating ? (
        <div className="flex gap-2 mb-1.5">
          {isInterrupted ? (
            <Button
              variant="outline"
              size="sm"
              onClick={handleContinue}
              className="flex-1 gap-1.5 text-primary border-primary/30 hover:bg-primary/5"
            >
              <Play size={14} weight="duotone" /> Continuar
            </Button>
          ) : (
            <Button
              variant="outline"
              size="sm"
              onClick={handleResume}
              disabled={!jobId}
              className="flex-1 gap-1.5 text-primary border-primary/30 hover:bg-primary/5"
            >
              <Clock size={14} weight="duotone" /> Reanudar / Ver progreso
            </Button>
          )}
        </div>
      ) : null}
      <div className="flex items-center gap-1.5">
        <Button
          variant="outline"
          size="sm"
          onClick={() => navigate(`/ova/${ova.id}/workspace`)}
          disabled={isGenerating || isDuplicating}
          title={isGenerating ? 'No disponible mientras se genera el OVA' : 'Abrir en workspace'}
          className="flex-1 gap-1.5 text-primary border-primary/30 hover:bg-primary/5"
        >
          <PencilSimple size={14} weight="duotone" /> Editar
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => onEditMetadata(ova)}
          disabled={isGenerating || isDuplicating}
          title={isGenerating ? 'No disponible mientras se genera el OVA' : 'Editar título y descripción'}
          className="flex-1 gap-1.5 text-primary border-primary/30 hover:bg-primary/5"
        >
          <FileText size={14} weight="duotone" /> Metadatos
        </Button>
      </div>
      <div className="flex flex-wrap items-center gap-1.5">
        <Button
          variant="outline"
          size="sm"
          onClick={() => onDuplicate(ova.id)}
          disabled={isGenerating || isDuplicating}
          title={isGenerating ? 'No disponible mientras se genera el OVA' : 'Duplicar OVA'}
          className="flex-1 gap-1.5"
        >
          <Copy size={14} weight="duotone" />{' '}
          {isDuplicating ? 'Duplicando...' : 'Duplicar'}
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => onDownload(ova.id, ova.title ?? '')}
          disabled={!isReady || isDownloading || isDuplicating}
          title={!isReady ? 'Solo disponible cuando el OVA está listo' : 'Descargar paquete SCORM'}
          className="flex-1 gap-1.5"
        >
          <DownloadSimple size={14} weight="duotone" />{' '}
          {isDownloading ? 'Descargando...' : 'Descargar'}
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => onMoveToTrash(ova)}
          disabled={isGenerating || isMoving || isDuplicating}
          title={isGenerating ? 'No se puede eliminar mientras se está generando' : 'Mover a la papelera'}
          className="flex-1 gap-1.5 text-destructive border-destructive/30 hover:bg-destructive/5"
        >
          <Trash size={14} weight="duotone" />{' '}
          {isMoving ? 'Moviendo...' : 'Papelera'}
        </Button>
      </div>
    </>
  )

  return (
    <OvaCardShell
      ova={ova}
      isSelected={isSelected}
      onToggleSelect={onToggleSelect}
      checkboxDisabled={isGenerating}
      dateValue={formatDate(ova.created_at as string | undefined)}
      extraBadges={extraBadges}
      footer={footer}
    />
  )
}

export const OvaCard = memo(OvaCardImpl)
