// frontend/src/features/ova-library/components/cards/trashed-ova-card.component.ts
import { Component, input, output } from "@angular/core";
import { ButtonComponent } from "@/core/components/ui/button.component";
import type { OvaListItem } from "@/features/ova-library/lib/types";
import { OvaCardShellComponent } from "./ova-card-shell.component";

@Component({
  selector: "gn-trashed-ova-card",
  standalone: true,
  imports: [OvaCardShellComponent, ButtonComponent],
  template: `
    <gn-ova-card-shell
      [ova]="ova()"
      [isSelected]="isSelected()"
      (onToggleSelect)="onToggleSelect.emit($event)"
      [rootClassName]="rootClass"
      dateLabel="Eliminado el"
      [dateValue]="formatDate(ova()['deleted_at'])"
      dateClassName="text-red-400 font-medium"
    >
      <div footer class="flex items-center gap-2 w-full">
        <gn-button
          variant="outline"
          size="sm"
          class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
          [disabled]="isRestoring() || isDeleting()"
          (onClick)="onRestore.emit(ova().id)"
        >
          <!-- ↩ -->
          {{ isRestoring() ? 'Restaurando...' : 'Restaurar' }}
        </gn-button>
        <gn-button
          variant="outline"
          size="sm"
          class="flex-1 text-destructive border-destructive/30 hover:bg-destructive/5"
          [disabled]="isRestoring() || isDeleting()"
          (onClick)="onPermanentDelete.emit(ova())"
        >
          <!-- 🗑 -->
          {{ isDeleting() ? 'Eliminando...' : 'Borrar definitivamente' }}
        </gn-button>
      </div>
    </gn-ova-card-shell>
  `,
})
export class TrashedOvaCardComponent {
  readonly ova = input.required<OvaListItem>();
  readonly isSelected = input(false);
  readonly isRestoring = input(false);
  readonly isDeleting = input(false);

  readonly onToggleSelect = output<string>();
  readonly onRestore = output<string>();
  readonly onPermanentDelete = output<OvaListItem>();

  get rootClass(): string {
    return `rounded-xl border bg-white p-5 shadow-sm transition ${
      this.isSelected() ? "border-primary/50 ring-1 ring-primary/20" : "border-border"
    }`;
  }

  formatDate(date: unknown): string {
    if (!date) return "";
    return new Date(date as string).toLocaleDateString();
  }
}

// archive/frontend-react-legacy/src/features/ova_library/components/cards/TrashedOvaCard.tsx
import { Button } from '@/core/components/ui/button'
import { formatDate } from '@/features/ova_library/lib/formatDate'
import type { OvaListItem } from '@/features/ova_library/lib/types'
import { OvaCardShell } from './OvaCardShell'

interface TrashedOvaCardProps {
  ova: OvaListItem
  isSelected: boolean
  onToggleSelect: (id: string) => void
  onRestore: (id: string) => void
  onPermanentDelete: (ova: OvaListItem) => void
  isRestoring: boolean
  isDeleting: boolean
}

export function TrashedOvaCard({
  ova,
  isSelected,
  onToggleSelect,
  onRestore,
  onPermanentDelete,
  isRestoring,
  isDeleting,
}: TrashedOvaCardProps) {
  const footer = (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={() => onRestore(ova.id)}
        disabled={isRestoring || isDeleting}
        className="flex-1 text-primary border-primary/30 hover:bg-primary/5"
      >
        {isRestoring ? 'Restaurando...' : '↩ Restaurar'}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={() => onPermanentDelete(ova)}
        disabled={isRestoring || isDeleting}
        className="flex-1 text-destructive border-destructive/30 hover:bg-destructive/5"
      >
        {isDeleting ? 'Eliminando...' : '🗑 Borrar definitivamente'}
      </Button>
    </div>
  )

  return (
    <OvaCardShell
      ova={ova}
      isSelected={isSelected}
      onToggleSelect={onToggleSelect}
      rootClassName={`rounded-xl border bg-white p-5 shadow-sm transition ${
        isSelected ? 'border-primary/50 ring-1 ring-primary/20' : 'border-border'
      }`}
      dateLabel="Eliminado el"
      dateValue={formatDate(ova.deleted_at as string | undefined)}
      dateClassName="text-red-400 font-medium"
      footer={footer}
    />
  )
}
