// frontend/src/features/profile/components/link-row.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input, input, output } from "@angular/core";

import { IconComponent } from "@/core/components/icon.component";

export interface LinkData {
  id: string;
  status: string;
  invite_email?: string;
  linked?: { full_name?: string; email?: string } | null;
  owner?: { email?: string };
}

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-link-row",
  imports: [CommonModule, IconComponent],
  template: `
    <div
      class="flex items-center gap-4 border-b border-border/50 px-5 py-4 last:border-0 hover:bg-accent/30 transition-colors"
    >
      <div
        class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary/20 to-accent-brand/20 text-sm font-bold text-primary shadow-sm border border-primary/20"
      >
        {{ getInitials() }}
      </div>
      <div class="min-w-0 flex-1">
        <p class="truncate text-sm font-bold">
          {{ getName() }}
        </p>
        <p class="truncate text-xs font-medium text-muted-foreground mt-0.5">
          @if (admin() && link.owner) {
            {{ link.owner.email }} ->
          }
          {{ getEmail() }} ·
          <span [ngClass]="link.status === 'activo' ? 'text-emerald-600' : 'text-amber-600'">
            {{ link.status }}
          </span>
        </p>
      </div>

      @if (isPending && isOwner()) {
        <button
          (click)="onResend.emit(link.id)"
          class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring hover:bg-accent hover:text-accent-foreground h-9 px-3 text-primary hover:bg-primary/10 hover:text-primary"
        >
          <gn-icon name="paper-plane-tilt" size="text-sm" class="mr-1.5" />
          Reenviar
        </button>
      }

      <button
        (click)="onDelete.emit(link.id)"
        class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-9 px-3 border-destructive/30 text-destructive hover:bg-destructive/10 hover:text-destructive shadow-sm"
      >
        {{ isPending ? "Cancelar" : "Desvincular" }}
      </button>
    </div>
  `,
})
export class LinkRowComponent {
  @Input({ required: true }) link!: LinkData;
  readonly admin = input(false);
  readonly isOwner = input(false);

  readonly onDelete = output<string>();
  readonly onResend = output<string>();

  get person() {
    return this.link.linked || { email: this.link.invite_email };
  }

  get isPending() {
    return this.link.status === "pending";
  }

  getInitials() {
    const p = this.person;
    return (p?.full_name || p?.email || "?").slice(0, 2).toUpperCase();
  }

  getName() {
    const p = this.person;
    return p?.full_name || p?.email || "Invitación pendiente";
  }

  getEmail() {
    const p = this.person;
    return p?.email || this.link.invite_email || "Sin email";
  }
}

// frontend/src/components/LinkRow.jsx
import { PaperPlaneTilt } from '@phosphor-icons/react'
import { Button } from '@/components/ui/button'

export default function LinkRow({ link, onDelete, onResend, admin = false, isOwner = false }) {
  const person = admin ? link.linked || { email: link.invite_email } : link.linked || { email: link.invite_email }
  const isPending = link.status === 'pending'
  return (
    <div className="flex items-center gap-4 border-b border-border/50 px-5 py-4 last:border-0 hover:bg-accent/30 transition-colors">
      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-primary/20 to-accent-brand/20 text-sm font-bold text-primary shadow-sm border border-primary/20">
        {(person?.full_name || person?.email || '?').slice(0, 2).toUpperCase()}
      </div>
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-bold">{person?.full_name || person?.email || 'Invitación pendiente'}</p>
        <p className="truncate text-xs font-medium text-muted-foreground mt-0.5">
          {admin && link.owner ? `${link.owner.email} -> ` : ''}
          {person?.email || link.invite_email || 'Sin email'} · <span className={link.status === 'activo' ? 'text-emerald-600' : 'text-amber-600'}>{link.status}</span>
        </p>
      </div>
      {isPending && isOwner && (
        <Button variant="ghost" size="sm" onClick={() => onResend(link.id)} className="text-primary hover:bg-primary/10 hover:text-primary">
          <PaperPlaneTilt size={14} weight="bold" className="mr-1.5" /> Reenviar
        </Button>
      )}
      <Button variant="outline" size="sm" onClick={() => onDelete(link.id)} className="border-destructive/30 text-destructive hover:bg-destructive/10 hover:text-destructive shadow-sm">
        {isPending ? 'Cancelar' : 'Desvincular'}
      </Button>
    </div>
  )
}
