// frontend/src/features/admin/components/role-form-modal.component.ts
import { Component, Input, input, output } from "@angular/core";
import { ButtonDirective } from "@/core/components/ui/button.directive";
import {
  DialogComponent,
  DialogContentComponent,
  DialogDescriptionComponent,
  DialogFooterComponent,
  DialogHeaderComponent,
  DialogTitleComponent,
} from "@/core/components/ui/dialog.component";
import { InputDirective } from "@/core/components/ui/input.directive";
import { LabelDirective } from "@/core/components/ui/label.directive";
import { AVAILABLE_PERMISSIONS } from "../lib/permissions";
import type { Role } from "../lib/types";

@Component({
  selector: "gn-role-form-modal",
  standalone: true,
  imports: [
    DialogComponent,
    DialogContentComponent,
    DialogHeaderComponent,
    DialogTitleComponent,
    DialogDescriptionComponent,
    DialogFooterComponent,
    ButtonDirective,
    LabelDirective,
    InputDirective,
  ],
  template: `
    <gn-dialog [open]="true" (openChange)="handleOpenChange($event)">
      <gn-dialog-content class="max-w-lg max-h-[92vh] overflow-y-auto">
        <gn-dialog-header>
          <gn-dialog-title>
            {{ editingRole ? 'Editar rol: ' + editingRole.name : 'Crear nuevo rol' }}
          </gn-dialog-title>
          <gn-dialog-description>
            {{
              editingRole
                ? 'Ajusta el nombre y la selección de permisos para este perfil del sistema.'
                : 'Elige un nombre único y asigna los permisos necesarios para este perfil.'
            }}
          </gn-dialog-description>
        </gn-dialog-header>

        <form (ngSubmit)="onSubmit.emit($event)" class="space-y-5">
          <div class="space-y-1.5">
            <label
              gnLabel
              for="role-name-input"
              class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
              >Nombre del rol</label
            >
            <input
              id="role-name-input"
              gnInput
              type="text"
              placeholder="Ej. docente, supervisor..."
              [value]="roleName()"
              (input)="onRoleNameChange.emit($event)"
              [disabled]="isSubmitting()"
            />
          </div>

          <div class="space-y-1.5">
            <label
              gnLabel
              for="role-description-input"
              class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
              >Descripción (Opcional)</label
            >
            <textarea
              id="role-description-input"
              class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 resize-none"
              placeholder="Breve descripción del propósito de este rol..."
              [value]="roleDescription()"
              (input)="onRoleDescriptionChange.emit($event)"
              [disabled]="isSubmitting()"
              rows="2"
            ></textarea>
          </div>

          <div class="space-y-2">
            <p gnLabel class="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Permisos del rol
            </p>
            <div class="space-y-2 max-h-56 overflow-y-auto pr-1">
              @for (perm of availablePermissions; track perm) {
                <label
                  class="flex items-start gap-3 rounded-lg border border-border bg-muted/20 p-3 hover:bg-muted/40 transition-colors cursor-pointer"
                >
                  <div class="mt-0.5 relative flex items-center justify-center">
                    <input
                      type="checkbox"
                      class="peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 appearance-none checked:bg-primary checked:border-primary"
                      [checked]="selectedPermissions().includes(perm.id)"
                      (change)="onPermissionToggle.emit(perm.id)"
                      [disabled]="isSubmitting()"
                    />
                    @if (selectedPermissions().includes(perm.id)) {
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="12"
                        height="12"
                        fill="white"
                        viewBox="0 0 256 256"
                        class="absolute pointer-events-none"
                      >
                        <path
                          d="M229.66,77.66l-128,128a8,8,0,0,1-11.32,0l-56-56a8,8,0,0,1,11.32-11.32L96,188.69,218.34,66.34a8,8,0,0,1,11.32,11.32Z"
                        ></path>
                      </svg>
                    }
                  </div>
                  <div class="flex flex-col">
                    <span class="text-sm font-semibold">{{ perm.label }}</span>
                    <span class="text-xs text-muted-foreground mt-0.5">{{ perm.desc }}</span>
                  </div>
                </label>
              }
            </div>
          </div>

          @if (formError) {
            <div
              class="rounded-lg border border-destructive/50 text-destructive p-4 bg-destructive/10 text-sm"
            >
              {{ formError }}
            </div>
          }

          <gn-dialog-footer>
            <button
              type="button"
              gnButton
              variant="ghost"
              (click)="onClose.emit()"
              [disabled]="isSubmitting()"
            >
              Cancelar
            </button>
            <button type="submit" gnButton [disabled]="isSubmitting() || !roleName().trim()">
              {{
                isSubmitting()
                  ? editingRole
                    ? 'Guardando...'
                    : 'Creando...'
                  : editingRole
                    ? 'Guardar cambios'
                    : 'Crear rol'
              }}
            </button>
          </gn-dialog-footer>
        </form>
      </gn-dialog-content>
    </gn-dialog>
  `,
})
export class RoleFormModalComponent {
  @Input() editingRole!: Role | null;
  readonly roleName = input("");
  readonly roleDescription = input("");
  readonly selectedPermissions = input<string[]>([]);
  @Input() formError = "";
  readonly isSubmitting = input(false);

  readonly onRoleNameChange = output<Event>();
  readonly onRoleDescriptionChange = output<Event>();
  readonly onPermissionToggle = output<string>();
  readonly onSubmit = output<Event>();
  readonly onClose = output<void>();

  availablePermissions = AVAILABLE_PERMISSIONS;

  handleOpenChange(open: boolean) {
    if (!open) {
      this.onClose.emit();
    }
  }
}

// frontend/src/components/RoleFormModal.jsx
import { AVAILABLE_PERMISSIONS } from '../lib/permissions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Checkbox } from '@/components/ui/checkbox'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog'

export function RoleFormModal({
  editingRole, roleName, roleDescription, selectedPermissions,
  formError, isSubmitting,
  onRoleNameChange, onRoleDescriptionChange, onPermissionToggle,
  onSubmit, onClose,
}) {
  return (
    <Dialog open={true} onOpenChange={(open) => { if (!open) onClose() }}>
      <DialogContent className="max-w-lg max-h-[92vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {editingRole ? `Editar rol: ${editingRole.name}` : 'Crear nuevo rol'}
          </DialogTitle>
          <DialogDescription>
            {editingRole
              ? 'Ajusta el nombre y la selección de permisos para este perfil del sistema.'
              : 'Elige un nombre único y asigna los permisos necesarios para este perfil.'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={onSubmit} className="space-y-5">
          <div className="space-y-1.5">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Nombre del rol
            </Label>
            <Input
              type="text"
              placeholder="Ej. docente, supervisor..."
              value={roleName}
              onChange={onRoleNameChange}
              disabled={isSubmitting}
            />
          </div>

          <div className="space-y-1.5">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Descripción (Opcional)
            </Label>
            <Textarea
              placeholder="Breve descripción del propósito de este rol..."
              value={roleDescription}
              onChange={onRoleDescriptionChange}
              disabled={isSubmitting}
              rows={2}
              className="resize-none"
            />
          </div>

          <div className="space-y-2">
            <Label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
              Permisos del rol
            </Label>
            <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
              {AVAILABLE_PERMISSIONS.map((perm) => (
                <label
                  key={perm.id}
                  className="flex items-start gap-3 rounded-lg border border-border bg-muted/20 p-3 hover:bg-muted/40 transition-colors cursor-pointer"
                >
                  <Checkbox
                    checked={selectedPermissions.includes(perm.id)}
                    onCheckedChange={() => onPermissionToggle(perm.id)}
                    disabled={isSubmitting}
                    className="mt-0.5"
                  />
                  <div className="flex flex-col">
                    <span className="text-sm font-semibold">{perm.label}</span>
                    <span className="text-xs text-muted-foreground mt-0.5">{perm.desc}</span>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {formError ? (
            <Alert variant="destructive">
              <AlertDescription>{formError}</AlertDescription>
            </Alert>
          ) : null}

          <DialogFooter>
            <Button type="button" variant="ghost" onClick={onClose} disabled={isSubmitting}>
              Cancelar
            </Button>
            <Button type="submit" disabled={isSubmitting || !roleName.trim()}>
              {isSubmitting
                ? (editingRole ? 'Guardando...' : 'Creando...')
                : (editingRole ? 'Guardar cambios' : 'Crear rol')}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
