// frontend/src/features/ova-library/pages/dashboard-stat-card.component.ts
import { CommonModule } from "@angular/common";
import { Component, Input } from "@angular/core";

@Component({
  selector: "gn-dashboard-stat-card",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="rounded-2xl border border-border/50 bg-background/50 p-6 shadow-sm transition-all hover:border-primary/20 hover:shadow-md">
      <p class="text-sm font-semibold text-muted-foreground">{{ label }}</p>
      <p class="mt-2 font-display text-4xl font-bold" [ngClass]="tone">
        {{ value }}
      </p>
      <p class="mt-2 text-xs font-medium text-muted-foreground/80">
        {{ sub }}
      </p>
    </div>
  `,
})
export class DashboardStatCardComponent {
  @Input({ required: true }) label!: string;
  @Input({ required: true }) value!: number;
  @Input({ required: true }) sub!: string;
  @Input({ required: true }) tone!: string;
}

// frontend/src/features/ova_library/pages/DashboardStatCard.tsx
// Tarjeta de estadística del Dashboard. Separada de los datos (helpers) para
// cumplir useComponentExportOnlyModules (un módulo = solo componentes).
import { m as motion } from 'motion/react'
import { itemVariants } from '@/features/ova_library/pages/DashboardPage.helpers'

interface StatCardProps {
  label: string
  value: number
  sub: string
  tone: string
}

export function StatCard({ label, value, sub, tone }: StatCardProps) {
  return (
    <motion.div
      variants={itemVariants}
      whileHover={{ y: -4 }}
      className="glass-card rounded-2xl p-6 transition"
    >
      <p className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground">
        {label}
      </p>
      <p
        className={`mt-3 text-5xl font-display font-semibold tracking-tight ${tone}`}
      >
        {value}
      </p>
      <p className="mt-2 text-xs font-medium text-muted-foreground">{sub}</p>
    </motion.div>
  )
}
