// frontend/src/core/components/search-input.tsx
import { Icon } from "@/core/components/icon";
import { Input } from "@/core/components/ui/input";
import { cn } from "@/core/lib/cn";

interface SearchInputProps {
  value: string;
  onValueChange: (value: string) => void;
  placeholder?: string;
  ariaLabel?: string;
  /** Clases extra del input; ganan en conflicto a las base. */
  inputClassName?: string;
  className?: string;
}

/**
 * Campo de búsqueda canónico: lupa a la izquierda (por encima del input, así
 * no queda tapada) y botón "Limpiar búsqueda" visible solo con texto.
 */
export function SearchInput({
  value,
  onValueChange,
  placeholder = "Buscar...",
  ariaLabel = "Buscar",
  inputClassName,
  className,
}: Readonly<SearchInputProps>) {
  return (
    <div className={cn("relative", className)}>
      <Icon
        name="magnifying-glass"
        size="text-lg"
        className="pointer-events-none absolute top-1/2 left-3.5 z-10 -translate-y-1/2 text-muted-foreground"
      />
      <Input
        type="search"
        value={value}
        placeholder={placeholder}
        aria-label={ariaLabel}
        onChange={(e) => {
          onValueChange(e.target.value);
        }}
        className={cn(
          "w-full pr-10 pl-10 [&::-webkit-search-cancel-button]:hidden",
          inputClassName,
        )}
      />
      {value !== "" && (
        <button
          type="button"
          onClick={() => {
            onValueChange("");
          }}
          aria-label="Limpiar búsqueda"
          className="absolute top-1/2 right-2.5 z-10 -translate-y-1/2 rounded-md p-1 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
        >
          <Icon name="x" size="text-base" />
        </button>
      )}
    </div>
  );
}

// frontend/src/core/components/ui/search-input.component.ts
import { ChangeDetectionStrategy, Component, input, output } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { HlmInput } from "@spartan-ng/helm/input";

import { IconComponent } from "@/core/components/icon.component";

/**
 * gn-search-input — campo de búsqueda canónico: lupa a la izquierda, input y
 * botón "Limpiar búsqueda" (visible solo con texto). El estilo del input se
 * ajusta por consumidor vía `inputClass`; hlmInput fusiona las clases y las
 * del consumidor ganan en conflicto.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-search-input",
  imports: [FormsModule, HlmInput, IconComponent],
  template: `
    <div class="relative">
      <gn-icon
        name="magnifying-glass"
        size="text-lg"
        class="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground"
      />
      <input
        type="text"
        hlmInput
        [placeholder]="placeholder()"
        [attr.aria-label]="ariaLabel()"
        [ngModel]="value()"
        (ngModelChange)="valueChange.emit($event)"
        [class]="'w-full pl-10 pr-10 ' + inputClass()"
      />
      @if (value()) {
        <button
          type="button"
          (click)="valueChange.emit('')"
          aria-label="Limpiar búsqueda"
          class="absolute right-2.5 top-1/2 -translate-y-1/2 rounded-md p-1 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
        >
          <gn-icon name="x" size="text-base" />
        </button>
      }
    </div>
  `,
})
export class SearchInputComponent {
  readonly value = input.required<string>();
  readonly placeholder = input("Buscar...");
  readonly ariaLabel = input("Buscar");
  readonly inputClass = input("");
  readonly valueChange = output<string>();
}
