// frontend/src/features/ova-workspace/components/modals/resource-preview-panel.component.ts
import { Component, input } from "@angular/core";
import { getResourcePreview } from "../../lib/resource-previews";
import type { Resource } from "@/core/lib/ova-types";

@Component({
  selector: "gn-resource-preview-panel",
  standalone: true,
  imports: [],
  template: `
    <aside [class]="className()">
      @if (!resource()) {
        <div class="flex flex-col items-center justify-center h-full p-6 text-center gap-3">
          <div
            class="w-14 h-14 rounded-2xl bg-muted/60 flex items-center justify-center text-2xl opacity-40"
          >
            📚
          </div>
          <p class="text-xs text-muted-foreground leading-relaxed max-w-[14rem]">
            Pasa el cursor sobre un recurso para previsualizarlo
          </p>
        </div>
      } @else {
        <div class="p-4 border-b border-border shrink-0">
          <div class="flex items-center gap-3">
            <div
              class="p-2 rounded-xl shrink-0 text-lg"
              [style.backgroundColor]="phaseColor() + '18'"
            >
              {{ resource()?.emoji || '📦' }}
            </div>
            <div class="min-w-0">
              <p class="font-semibold text-sm text-foreground leading-tight">
                {{ resource()?.tipo }}
              </p>
              <span class="text-xs font-medium text-muted-foreground"
                >Interactividad {{ resource()?.interactividad }}</span
              >
            </div>
          </div>
        </div>

        @if (preview) {
          <div class="p-4 flex flex-col gap-3 overflow-y-auto">
            <div>
              <p
                class="text-[10px] font-bold uppercase tracking-widest mb-2"
                [style.color]="phaseColor()"
              >
                Qué genera
              </p>
              <ul class="space-y-1.5">
                @for (b of preview.bullets; track $index) {
                  <li class="flex items-start gap-2 text-xs text-foreground">
                    <span
                      class="mt-1 h-1.5 w-1.5 rounded-full shrink-0"
                      [style.backgroundColor]="phaseColor()"
                    ></span>
                    {{ b }}
                  </li>
                }
              </ul>
            </div>
            <div class="pt-3 border-t border-border">
              <p class="text-[10px] text-muted-foreground">
                <span class="font-semibold">Formato: </span>{{ preview.format }}
              </p>
            </div>
          </div>
        } @else {
          <div class="p-4 text-xs text-muted-foreground">
            Vista previa no disponible para este recurso.
          </div>
        }
      }
    </aside>
  `,
})
export class ResourcePreviewPanelComponent {
  readonly resource = input<Resource | null>(null);
  readonly phaseKey = input("");
  readonly phaseColor = input("#3B82F6");
  readonly className = input(
    "hidden sm:flex flex-col w-72 border-l border-border bg-muted/20 shrink-0 overflow-y-auto",
  );

  get preview() {
    const resource = this.resource();
    if (!resource) return null;
    return getResourcePreview(this.phaseKey(), resource.id);
  }
}

// frontend-react-legacy/src/features/ova_library/components/modals/ResourcePreviewPanel.tsx
import { BookBookmark } from '@phosphor-icons/react'
import type { ComponentType } from 'react'
import { RESOURCE_ICONS } from '@/features/ova_library/lib/resourceIcons'
import { RESOURCE_PREVIEWS } from '@/features/ova_library/lib/resourcePreviews'
import { RESOURCE_WIREFRAMES } from '@/features/ova_library/lib/resourceWireframes'
import type { Resource } from '@/features/student/lib/types'

interface ResourcePreviewPanelProps {
  resource: Resource | null
  phaseKey: string
  phaseColor: string
  className?: string
}

const INTERACTIVIDAD_COLOR: Record<string, string> = {
  Alta: 'text-primary',
  Media: 'text-accent-brand',
  Baja: 'text-muted-foreground',
}

function Placeholder() {
  return (
    <div className="flex flex-col items-center justify-center h-full p-6 text-center gap-3">
      <div className="w-14 h-14 rounded-2xl bg-muted/60 flex items-center justify-center">
        <BookBookmark
          size={26}
          weight="duotone"
          className="text-muted-foreground/40"
        />
      </div>
      <p className="text-xs text-muted-foreground leading-relaxed max-w-[14rem]">
        Pasa el cursor sobre un recurso para previsualizarlo
      </p>
    </div>
  )
}

export function ResourcePreviewPanel({
  resource,
  phaseKey,
  phaseColor,
  className,
}: ResourcePreviewPanelProps) {
  if (!resource)
    return (
      <aside className={className}>
        <Placeholder />
      </aside>
    )

  const key = `${phaseKey}:${resource.id}`
  const preview = RESOURCE_PREVIEWS[key]
  const Icon = (RESOURCE_ICONS[key] ?? BookBookmark) as ComponentType<{
    size: number
    weight: string
    style?: React.CSSProperties
  }>
  const Wireframe = RESOURCE_WIREFRAMES[key] as ComponentType | undefined

  return (
    <aside className={className}>
      <div className="p-4 border-b border-border shrink-0">
        <div className="flex items-center gap-3">
          <div
            className="p-2 rounded-xl shrink-0"
            style={{ backgroundColor: `${phaseColor}18` }}
          >
            <Icon size={22} weight="duotone" style={{ color: phaseColor }} />
          </div>
          <div className="min-w-0">
            <p className="font-semibold text-sm text-foreground leading-tight">
              {resource.tipo}
            </p>
            <span
              className={`text-xs font-medium ${INTERACTIVIDAD_COLOR[resource.interactividad ?? ''] ?? INTERACTIVIDAD_COLOR.Baja}`}
            >
              Interactividad {resource.interactividad}
            </span>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {Wireframe && (
          <div className="p-4 border-b border-border">
            <p className="text-[10px] font-bold uppercase tracking-widest mb-2 text-muted-foreground">
              Vista previa
            </p>
            <div className="rounded-lg border border-border bg-white overflow-hidden">
              <Wireframe />
            </div>
          </div>
        )}

        {preview && (
          <div className="p-4 flex flex-col gap-3">
            <div>
              <p
                className="text-[10px] font-bold uppercase tracking-widest mb-2"
                style={{ color: phaseColor }}
              >
                Qué genera
              </p>
              <ul className="space-y-1.5">
                {preview.bullets.map((b: string, i: number) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 text-xs text-foreground"
                  >
                    <span
                      className="mt-1 h-1.5 w-1.5 rounded-full shrink-0"
                      style={{ backgroundColor: phaseColor }}
                    />
                    {b}
                  </li>
                ))}
              </ul>
            </div>
            <div className="pt-3 border-t border-border">
              <p className="text-[10px] text-muted-foreground">
                <span className="font-semibold">Formato: </span>
                {preview.format}
              </p>
            </div>
          </div>
        )}
      </div>
    </aside>
  )
}
