// frontend/src/features/admin/components/users/edit-user-modal.component.ts
import { Component, inject, type OnInit, input, output } from "@angular/core";
import { FormBuilder, type FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import { ButtonDirective } from "@/core/components/ui/button.directive";
import {
  DialogComponent,
  DialogContentComponent,
  DialogFooterComponent,
  DialogHeaderComponent,
  DialogTitleComponent,
} from "@/core/components/ui/dialog.component";
import { InputDirective } from "@/core/components/ui/input.directive";
import { LabelDirective } from "@/core/components/ui/label.directive";
import type { AdminUser } from "../../lib/types";

@Component({
  selector: "gn-edit-user-modal",
  standalone: true,
  imports: [
    ReactiveFormsModule,
    DialogComponent,
    DialogContentComponent,
    DialogHeaderComponent,
    DialogTitleComponent,
    DialogFooterComponent,
    InputDirective,
    LabelDirective,
    ButtonDirective,
  ],
  template: `
    <gn-dialog [open]="true" (openChange)="handleOpenChange($event)">
      <gn-dialog-content class="max-w-md max-h-[85vh] overflow-y-auto">
        <gn-dialog-header>
          <gn-dialog-title>Editar Perfil: {{ user().full_name || user().email }}</gn-dialog-title>
        </gn-dialog-header>

        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4">
          <!-- Nombre Completo -->
          <div class="space-y-1.5">
            <label
              gnLabel
              for="edit-full-name"
              class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
              >Nombre Completo</label
            >
            <input
              gnInput
              id="edit-full-name"
              type="text"
              placeholder="Ej: Juan Pérez"
              formControlName="full_name"
            />
            @if (form.get('full_name')?.errors?.['required'] && form.get('full_name')?.touched) {
              <p class="text-xs text-destructive">El nombre es requerido.</p>
            }
          </div>

          <!-- Email -->
          <div class="space-y-1.5">
            <label
              gnLabel
              for="edit-email"
              class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
              >Correo Electrónico</label
            >
            <input
              gnInput
              id="edit-email"
              type="email"
              placeholder="ejemplo@correo.com"
              formControlName="email"
            />
            @if (form.get('email')?.errors?.['email'] && form.get('email')?.touched) {
              <p class="text-xs text-destructive">Correo inválido.</p>
            }
          </div>

          <!-- Código Universitario -->
          <div class="space-y-1.5">
            <label
              gnLabel
              for="edit-uni-id"
              class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
              >Código Universitario (UPAO)</label
            >
            <input
              gnInput
              id="edit-uni-id"
              type="number"
              min="1"
              placeholder="Ej: 257022"
              formControlName="university_id"
            />
            <p class="text-[10px] text-muted-foreground mt-0.5">
              Se autocompletará con ceros a la izquierda a 9 dígitos.
            </p>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <!-- Sexo -->
            <div class="space-y-1.5">
              <label
                gnLabel
                for="edit-gender"
                class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
                >Sexo / Género</label
              >
              <select
                id="edit-gender"
                formControlName="gender"
                class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <option value="masculino">Masculino</option>
                <option value="femenino">Femenino</option>
                <option value="otro">Otro</option>
              </select>
            </div>

            <!-- Teléfono -->
            <div class="space-y-1.5">
              <label
                gnLabel
                for="edit-phone"
                class="text-xs font-bold uppercase tracking-wider text-muted-foreground"
                >Teléfono</label
              >
              <input
                gnInput
                id="edit-phone"
                type="text"
                placeholder="Ej: +51987285992"
                formControlName="phone_number"
              />
            </div>
          </div>

          <gn-dialog-footer class="pt-4 border-t border-border mt-4">
            <button type="button" gnButton variant="outline" (click)="onClose.emit()">
              Cancelar
            </button>
            <button type="submit" gnButton [disabled]="isSubmitting">Guardar Cambios</button>
          </gn-dialog-footer>
        </form>
      </gn-dialog-content>
    </gn-dialog>
  `,
})
export class EditUserModalComponent implements OnInit {
  readonly user = input.required<AdminUser>();

  readonly onClose = output<void>();
  readonly onSave = output<Record<string, unknown>>();

  fb = inject(FormBuilder);
  form!: FormGroup;
  isSubmitting = false;

  ngOnInit() {
    const user = this.user();
    this.form = this.fb.group({
      full_name: [this.user().full_name || "", Validators.required],
      email: [this.user().email || "", [Validators.required, Validators.email]],
      university_id: [user.university_id ? String(user.university_id) : ""],
      gender: [this.user().gender || "otro"],
      phone_number: [this.user().phone_number || ""],
    });
  }

  handleOpenChange(open: boolean) {
    if (!open) this.onClose.emit();
  }

  onSubmit() {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.isSubmitting = true;
    const value = this.form.value;
    const payload = {
      full_name: value.full_name.trim(),
      email: value.email.trim(),
      university_id: value.university_id ? parseInt(value.university_id, 10) : null,
      gender: value.gender || null,
      phone_number: value.phone_number?.trim() || null,
    };

    this.onSave.emit(payload);
  }
}

// frontend/src/features/admin/components/users/EditUserModal.jsx
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button } from '@/core/components/ui/button'
import { Input } from '@/core/components/ui/input'
import { Label } from '@/core/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/core/components/ui/select'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/core/components/ui/dialog'
import { userEditSchema } from '@/features/profile/schemas/user.js'

function Field({ label, htmlFor, error, children }) {
  return (
    <div className="space-y-1.5">
      <Label htmlFor={htmlFor} className="text-xs font-bold uppercase tracking-wider text-muted-foreground">
        {label}
      </Label>
      {children}
      {error ? <p className="text-xs text-destructive">{error}</p> : null}
    </div>
  )
}

export function EditUserModal({ user, onClose, onSave }) {
  const {
    register,
    control,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm({
    resolver: zodResolver(userEditSchema),
    defaultValues: {
      full_name: user.full_name || '',
      email: user.email || '',
      university_id: user.university_id ? String(user.university_id) : '',
      gender: user.gender || 'otro',
      phone_number: user.phone_number || '',
    },
  })

  const onSubmit = async (form) => {
    const payload = {
      full_name: form.full_name.trim(),
      email: form.email.trim(),
      university_id: form.university_id ? parseInt(form.university_id, 10) : null,
      gender: form.gender || null,
      phone_number: form.phone_number?.trim() || null,
    }
    const ok = await onSave(user.id, payload)
    if (ok) onClose()
  }

  return (
    <Dialog open={true} onOpenChange={(open) => { if (!open) onClose() }}>
      <DialogContent className="max-w-md max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Editar Perfil: {user.full_name || user.email}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <Field label="Nombre Completo" htmlFor="edit-full-name" error={errors.full_name?.message}>
            <Input id="edit-full-name" type="text" placeholder="Ej: Juan Pérez" {...register('full_name')} />
          </Field>
          <Field label="Correo Electrónico" htmlFor="edit-email" error={errors.email?.message}>
            <Input id="edit-email" type="email" placeholder="ejemplo@correo.com" {...register('email')} />
          </Field>
          <Field label="Código Universitario (UPAO)" htmlFor="edit-uni-id">
            <Input id="edit-uni-id" type="number" min="1" placeholder="Ej: 257022" {...register('university_id')} />
            <p className="text-[10px] text-muted-foreground mt-0.5">Se autocompletará con ceros a la izquierda a 9 dígitos.</p>
          </Field>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Field label="Sexo / Género" htmlFor="edit-gender">
              <Controller
                control={control}
                name="gender"
                render={({ field }) => (
                  <Select value={field.value} onValueChange={field.onChange}>
                    <SelectTrigger id="edit-gender">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="masculino">Masculino</SelectItem>
                      <SelectItem value="femenino">Femenino</SelectItem>
                      <SelectItem value="otro">Otro</SelectItem>
                    </SelectContent>
                  </Select>
                )}
              />
            </Field>
            <Field label="Teléfono" htmlFor="edit-phone" error={errors.phone_number?.message}>
              <Input id="edit-phone" type="text" placeholder="Ej: +51987285992" {...register('phone_number')} />
            </Field>
          </div>
          <DialogFooter className="pt-4 border-t border-border">
            <Button type="button" variant="outline" onClick={onClose}>
              Cancelar
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              Guardar Cambios
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
