// frontend-react-legacy/src/features/admin/components/users/StatusBadge.tsx
import { StateBadge } from '@/core/components/ui/StateBadge'
import type { AdminUser } from '../../lib/types'
import { isLockedOut } from './statusHelpers'

interface Props {
  user: AdminUser
}

export function UserStatusBadge({ user }: Props) {
  if (!user.is_active) {
    return <StateBadge status="neutral">Inactivo</StateBadge>
  }
  if (isLockedOut(user)) {
    return (
      <StateBadge
        status="error"
        title={`Bloqueado hasta ${user.locked_until ? new Date(user.locked_until).toLocaleString('es-PE') : ''}`}
      >
        🔒 Bloqueado
      </StateBadge>
    )
  }
  return <StateBadge status="success">Activo</StateBadge>
}

// frontend/src/features/admin/components/users/status-badge.component.ts
import { Component, input } from "@angular/core";

import type { AdminUser } from "../../lib/types";
import { isLockedOut } from "./statusHelpers";

@Component({
  selector: "gn-user-status-badge",
  standalone: true,
  imports: [],
  template: `
    @if (!user().is_active) {
      <span
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-muted text-muted-foreground border-border"
      >
        Inactivo
      </span>
    }

    @if (user().is_active && isLocked) {
      <span
        [title]="lockedTitle"
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-destructive/10 text-destructive border-destructive/20"
      >
        🔒 Bloqueado
      </span>
    }

    @if (user().is_active && !isLocked) {
      <span
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-emerald-500/10 text-emerald-600 border-emerald-500/20"
      >
        Activo
      </span>
    }
  `,
})
export class UserStatusBadgeComponent {
  readonly user = input.required<AdminUser>();

  get isLocked(): boolean {
    return isLockedOut(this.user());
  }

  get lockedTitle(): string {
    const user = this.user();
    if (!user.locked_until) return "";
    return `Bloqueado hasta ${new Date(user.locked_until).toLocaleString("es-PE")}`;
  }
}
