// frontend/src/components/admin/users/UserActionMenu.jsx
import { isLockedOut } from './statusHelpers.js'

function Item({ onClick, tone = 'text-foreground hover:bg-muted', icon, label, disabled }) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      className={`w-full px-4 py-2 text-xs flex items-center gap-2 transition-colors ${
        disabled ? 'text-muted-foreground/40 cursor-not-allowed' : `${tone} cursor-pointer`
      }`}
    >
      <span>{icon}</span> {label}
    </button>
  )
}

export function UserActionMenu({
  user,
  onEdit,
  onToggleStatus,
  onUnlock,
  onSendResetEmail,
  onSendResetWhatsApp,
  onClose,
}) {
  function close(fn) {
    onClose?.()
    return fn
  }
  return (
    <div className="absolute right-2 sm:right-5 mt-1 w-52 rounded-lg bg-popover shadow-xl border border-border py-1.5 z-20 text-left">
      <Item icon="✏️" label="Editar Perfil" onClick={() => close(onEdit)()} />
      <Item
        icon={user.is_active ? '🚫' : '✅'}
        label={user.is_active ? 'Desactivar Cuenta' : 'Activar Cuenta'}
        tone={user.is_active ? 'text-accent-brand hover:bg-accent-brand/10' : 'text-primary hover:bg-primary/10'}
        onClick={() => close(() => onToggleStatus(user.id, !user.is_active))()}
      />
      {isLockedOut(user) && (
        <Item
          icon="🔓"
          label="Desbloquear Cuenta"
          tone="text-primary hover:bg-primary/10"
          onClick={() => close(() => onUnlock(user.id))()}
        />
      )}
      <div className="border-t border-border my-1" />
      <Item icon="✉️" label="Restablecer por Correo" onClick={() => close(() => onSendResetEmail(user.id))()} />
      {user.phone_number ? (
        <Item
          icon="💬"
          label="Enlace WhatsApp"
          tone="text-primary hover:bg-primary/10"
          onClick={() => close(() => onSendResetWhatsApp(user.id))()}
        />
      ) : (
        <Item icon="💬" label="Sin Teléfono" disabled />
      )}
    </div>
  )
}

// frontend/src/features/admin/components/users/user-action-menu.component.ts
import { CommonModule } from "@angular/common";
import { Component, Input, output } from "@angular/core";
import type { AdminUser } from "../../lib/types";
import { isLockedOut } from "./statusHelpers";

@Component({
  selector: "gn-user-action-menu",
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="py-1">
      <button
        (click)="onEdit.emit()"
        class="w-full text-left px-4 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
      >
        <span>✏️</span> Editar Perfil
      </button>

      <button
        (click)="onToggleStatus.emit(!user.is_active)"
        class="w-full text-left px-4 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
        [ngClass]="user.is_active ? 'text-accent-brand' : 'text-primary'"
      >
        <span>{{ user.is_active ? '🚫' : '✅' }}</span>
        {{ user.is_active ? 'Desactivar Cuenta' : 'Activar Cuenta' }}
      </button>

      @if (isLocked) {
        <button
          (click)="onUnlock.emit(user.id)"
          class="w-full text-left px-4 py-2 text-sm text-primary hover:bg-accent hover:text-accent-foreground"
        >
          <span>🔓</span> Desbloquear Cuenta
        </button>
      }

      <div class="h-px bg-border my-1"></div>

      <button
        (click)="onSendResetEmail.emit(user.id)"
        class="w-full text-left px-4 py-2 text-sm hover:bg-accent hover:text-accent-foreground"
      >
        <span>✉️</span> Restablecer por Correo
      </button>

      @if (user.phone_number) {
        <button
          (click)="onSendResetWhatsApp.emit(user.id)"
          class="w-full text-left px-4 py-2 text-sm text-primary hover:bg-accent hover:text-accent-foreground"
        >
          <span>💬</span> Enlace WhatsApp
        </button>
      }

      @if (!user.phone_number) {
        <button disabled class="w-full text-left px-4 py-2 text-sm opacity-50 cursor-not-allowed">
          <span>💬</span> Sin Teléfono
        </button>
      }
    </div>
  `,
})
export class UserActionMenuComponent {
  @Input({ required: true }) user!: AdminUser;

  readonly onEdit = output<void>();
  readonly onToggleStatus = output<boolean>();
  readonly onUnlock = output<string>();
  readonly onSendResetEmail = output<string>();
  readonly onSendResetWhatsApp = output<string>();

  get isLocked(): boolean {
    return isLockedOut(this.user);
  }
}
