// frontend/src/features/admin/components/users/user-action-menu.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input, output } from "@angular/core";
import { HlmDropdownMenuItem, HlmDropdownMenuSeparator } from "@spartan-ng/helm/dropdown-menu";

import { IconComponent } from "@/core/components/icon.component";

import type { AdminUser } from "../../lib/types";
import { isLockedOut } from "./status-helpers";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-user-action-menu",
  imports: [CommonModule, HlmDropdownMenuItem, HlmDropdownMenuSeparator, IconComponent],
  template: `
    <div class="py-1">
      <button hlmDropdownMenuItem (click)="onEdit.emit()">
        <gn-icon name="pencil-simple" size="text-sm" /> Editar Perfil
      </button>

      <button
        hlmDropdownMenuItem
        (click)="onToggleStatus.emit(!user.is_active)"
        [ngClass]="user.is_active ? 'text-accent-brand' : 'text-primary'"
      >
        <gn-icon [name]="user.is_active ? 'prohibit' : 'check-circle'" size="text-sm" />
        {{ user.is_active ? "Desactivar Cuenta" : "Activar Cuenta" }}
      </button>

      @if (isLocked) {
        <button hlmDropdownMenuItem class="text-primary" (click)="onUnlock.emit(user.id)">
          <gn-icon name="lock-open" size="text-sm" /> Desbloquear Cuenta
        </button>
      }

      <div hlmDropdownMenuSeparator></div>

      <button hlmDropdownMenuItem (click)="onSendResetEmail.emit(user.id)">
        <gn-icon name="envelope" size="text-sm" /> Restablecer por Correo
      </button>
    </div>
  `,
})
export class UserActionMenuComponent {
  @Input({ required: true }) user!: AdminUser;

  readonly onEdit = output();
  readonly onToggleStatus = output<boolean>();
  readonly onUnlock = output<string>();
  readonly onSendResetEmail = output<string>();

  get isLocked(): boolean {
    return isLockedOut(this.user);
  }
}

// frontend/src/features/admin/components/users/user-action-menu.tsx
import { Icon } from "@/core/components/icon";
import { Button } from "@/core/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/core/components/ui/dropdown-menu";

import type { AdminUser } from "../../lib/types";
import { isLockedOut } from "./status-helpers";

interface UserActionMenuProps {
  user: AdminUser;
  onEdit: () => void;
  onToggleStatus: (isActive: boolean) => void;
  onUnlock: () => void;
  onSendResetEmail: () => void;
}

export function UserActionMenu({
  user,
  onEdit,
  onToggleStatus,
  onUnlock,
  onSendResetEmail,
}: Readonly<UserActionMenuProps>) {
  const isActive = user.is_active === true;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="rounded-xl text-xs">
          Acción ▾
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-52">
        <DropdownMenuItem onSelect={onEdit}>
          <Icon name="pencil-simple" size="text-sm" /> Editar Perfil
        </DropdownMenuItem>
        <DropdownMenuItem
          onSelect={() => {
            onToggleStatus(!isActive);
          }}
          className={isActive ? "text-accent-brand" : "text-primary"}
        >
          <Icon name={isActive ? "prohibit" : "check-circle"} size="text-sm" />
          {isActive ? "Desactivar Cuenta" : "Activar Cuenta"}
        </DropdownMenuItem>
        {isLockedOut(user) && (
          <DropdownMenuItem onSelect={onUnlock} className="text-primary">
            <Icon name="lock-open" size="text-sm" /> Desbloquear Cuenta
          </DropdownMenuItem>
        )}
        <DropdownMenuSeparator />
        <DropdownMenuItem onSelect={onSendResetEmail}>
          <Icon name="envelope" size="text-sm" /> Restablecer por Correo
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
