// frontend/src/features/ova-workspace/components/modals/add-resource-modal.component.ts
import { Component, input, output } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { ButtonComponent } from "@/core/components/ui/button.component";
import {
  DialogComponent,
  DialogContentComponent,
  DialogDescriptionComponent,
  DialogFooterComponent,
  DialogHeaderComponent,
  DialogTitleComponent,
} from "@/core/components/ui/dialog.component";

const MAX_PHASES_PER_TYPE = 4;

@Component({
  selector: "gn-add-resource-modal",
  standalone: true,
  imports: [
    FormsModule,
    DialogComponent,
    DialogContentComponent,
    DialogHeaderComponent,
    DialogFooterComponent,
    DialogTitleComponent,
    DialogDescriptionComponent,
    ButtonComponent,
  ],
  template: `
    <gn-dialog [open]="open()" (openChange)="onOpenChange.emit($event)">
      <gn-dialog-content class="max-w-md">
        <gn-dialog-header>
          <gn-dialog-title
            >Añadir recurso — <span class="capitalize">{{ phaseType() }}</span></gn-dialog-title
          >
          <gn-dialog-description>
            @if (isFull) {
              Esta fase ya tiene el máximo de {{ MAX_PHASES_PER_TYPE }} recursos.
            }
            @if (!isFull) {
              Describe el nuevo recurso para la fase "{{ phaseType() }}" ({{ currentCount() }}/{{
                MAX_PHASES_PER_TYPE
              }}).
            }
          </gn-dialog-description>
        </gn-dialog-header>

        @if (!isFull) {
          <div class="space-y-3 py-1">
            <textarea
              class="w-full rounded-md border border-border bg-background px-3 py-2 text-sm resize-y min-h-[80px] focus:outline-none focus:ring-2 focus:ring-ring"
              [placeholder]="
                'Ej: Añade un ejemplo práctico de ' + phaseType() + ' con código Python'
              "
              [(ngModel)]="prompt"
              [disabled]="loading"
              (keydown)="handleKeyDown($event)"
            ></textarea>
            <p class="text-[10px] text-muted-foreground">Ctrl+Enter para guardar</p>
          </div>
        }

        <gn-dialog-footer>
          <gn-button type="button" variant="ghost" (click)="onOpenChange.emit(false)">
            Cancelar
          </gn-button>
          @if (!isFull) {
            <gn-button
              type="button"
              [disabled]="!prompt.trim() || loading"
              (click)="handleSubmit()"
            >
              {{ loading ? 'Añadiendo…' : 'Añadir recurso' }}
            </gn-button>
          }
        </gn-dialog-footer>
      </gn-dialog-content>
    </gn-dialog>
  `,
})
export class AddResourceModalComponent {
  readonly open = input(false);
  readonly phaseType = input("");
  readonly currentCount = input(0);

  readonly onOpenChange = output<boolean>();
  readonly onAdd = output<{
    phaseType: string;
    prompt: string;
  }>();

  MAX_PHASES_PER_TYPE = MAX_PHASES_PER_TYPE;
  prompt = "";
  loading = false;

  get isFull() {
    return this.currentCount() >= this.MAX_PHASES_PER_TYPE;
  }

  handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
      this.handleSubmit();
    }
  }

  async handleSubmit() {
    if (!this.prompt.trim() || this.loading || this.isFull) return;
    this.loading = true;
    try {
      this.onAdd.emit({ phaseType: this.phaseType(), prompt: this.prompt.trim() });
      this.prompt = "";
      this.onOpenChange.emit(false);
    } finally {
      // Small timeout to allow animation before disabling loading visually
      setTimeout(() => (this.loading = false), 300);
    }
  }
}

// frontend/src/components/workspace/AddResourceModal.jsx
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from '@/components/ui/dialog'

const MAX_PHASES_PER_TYPE = 4

/**
 * HU-032 — Modal para añadir un nuevo recurso a una fase del OVA.
 * Validates max 4 per phase_type. Submit triggers addOvaPhase callback.
 */
export function AddResourceModal({ open, onOpenChange, phaseType, currentCount, onAdd }) {
  const [prompt, setPrompt] = useState('')
  const [loading, setLoading] = useState(false)

  const isFull = currentCount >= MAX_PHASES_PER_TYPE

  async function handleSubmit() {
    if (!prompt.trim() || loading || isFull) return
    setLoading(true)
    try {
      await onAdd?.(phaseType, prompt.trim())
      setPrompt('')
      onOpenChange(false)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Añadir recurso — {phaseType}</DialogTitle>
          <DialogDescription>
            {isFull
              ? `Esta fase ya tiene el máximo de ${MAX_PHASES_PER_TYPE} recursos.`
              : `Describe el nuevo recurso para la fase "${phaseType}" (${currentCount}/${MAX_PHASES_PER_TYPE}).`}
          </DialogDescription>
        </DialogHeader>

        {!isFull ? (
          <div className="space-y-3 py-1">
            <textarea
              className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm resize-y min-h-[80px] focus:outline-none focus:ring-2 focus:ring-ring"
              placeholder={`Ej: "Añade un ejemplo práctico de ${phaseType} con código Python"`}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              disabled={loading}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) void handleSubmit()
              }}
            />
            <p className="text-[10px] text-muted-foreground">Ctrl+Enter para guardar</p>
          </div>
        ) : null}

        <DialogFooter>
          <Button type="button" variant="ghost" onClick={() => onOpenChange(false)}>
            Cancelar
          </Button>
          {!isFull ? (
            <Button
              type="button"
              disabled={!prompt.trim() || loading}
              onClick={handleSubmit}
            >
              {loading ? 'Añadiendo…' : 'Añadir recurso'}
            </Button>
          ) : null}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
