// frontend/src/features/ova-library/components/cards/ova-list-pagination.component.ts
import { Component, Input, input, output } from "@angular/core";
import { ButtonComponent } from "@/core/components/ui/button.component";

@Component({
  selector: "gn-ova-list-pagination",
  standalone: true,
  imports: [ButtonComponent],
  template: `
    @if (totalPages > 1) {
      <div class="flex items-center justify-between border-t border-border pt-4 px-1">
        <p class="text-xs text-muted-foreground font-medium">
          Página <span class="text-foreground font-bold">{{ currentPage() }}</span> de
          <span class="text-foreground font-bold">{{ totalPages }}</span>
        </p>
        <div class="flex gap-2">
          <gn-button
            variant="outline"
            size="sm"
            (onClick)="onPageChange.emit(currentPage() - 1)"
            [disabled]="currentPage() === 1"
          >
            <!-- <CaretLeft /> -->
            Anterior
          </gn-button>
          <gn-button
            variant="outline"
            size="sm"
            (onClick)="onPageChange.emit(currentPage() + 1)"
            [disabled]="currentPage() === totalPages"
          >
            Siguiente
            <!-- <CaretRight /> -->
          </gn-button>
        </div>
      </div>
    }
  `,
})
export class OvaListPaginationComponent {
  readonly currentPage = input.required<number>();
  @Input({ required: true }) totalPages!: number;

  readonly onPageChange = output<number>();
}

// frontend/src/features/ova_library/components/cards/OvaListPagination.jsx
import { CaretLeft, CaretRight } from '@phosphor-icons/react'
import { Button } from '@/core/components/ui/button'

export function OvaListPagination({ currentPage, totalPages, onPageChange }) {
  if (totalPages <= 1) return null
  return (
    <div className="flex items-center justify-between border-t border-border pt-4 px-1">
      <p className="text-xs text-muted-foreground font-medium">
        Página <span className="text-foreground font-bold">{currentPage}</span> de{' '}
        <span className="text-foreground font-bold">{totalPages}</span>
      </p>
      <div className="flex gap-2">
        <Button
          variant="outline"
          size="sm"
          onClick={() => onPageChange(currentPage - 1)}
          disabled={currentPage === 1}
        >
          <CaretLeft size={16} weight="bold" />
          Anterior
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={() => onPageChange(currentPage + 1)}
          disabled={currentPage === totalPages}
        >
          Siguiente
          <CaretRight size={16} weight="bold" />
        </Button>
      </div>
    </div>
  )
}
