// frontend/src/features/admin/components/users/status-badge.component.ts
import { Component, input } from "@angular/core";

import type { AdminUser } from "../../lib/types";
import { isLockedOut } from "./statusHelpers";

@Component({
  selector: "gn-user-status-badge",
  standalone: true,
  imports: [],
  template: `
    @if (!user().is_active) {
      <span
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-muted text-muted-foreground border-border"
      >
        Inactivo
      </span>
    }

    @if (user().is_active && isLocked) {
      <span
        [title]="lockedTitle"
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-destructive/10 text-destructive border-destructive/20"
      >
        🔒 Bloqueado
      </span>
    }

    @if (user().is_active && !isLocked) {
      <span
        class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm bg-emerald-500/10 text-emerald-600 border-emerald-500/20"
      >
        Activo
      </span>
    }
  `,
})
export class UserStatusBadgeComponent {
  readonly user = input.required<AdminUser>();

  get isLocked(): boolean {
    return isLockedOut(this.user());
  }

  get lockedTitle(): string {
    const user = this.user();
    if (!user.locked_until) return "";
    return `Bloqueado hasta ${new Date(user.locked_until).toLocaleString("es-PE")}`;
  }
}

// frontend/src/components/admin/users/StatusBadge.jsx
import { isLockedOut } from './statusHelpers.js'

export function UserStatusBadge({ user }) {
  if (!user.is_active) {
    return (
      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-600">
        Inactivo
      </span>
    )
  }
  if (isLockedOut(user)) {
    return (
      <span
        className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-rose-100 text-rose-800"
        title={`Bloqueado hasta ${new Date(user.locked_until).toLocaleString()}`}
      >
        🔒 Bloqueado
      </span>
    )
  }
  return (
    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-emerald-100 text-emerald-800">
      Activo
    </span>
  )
}
