// frontend/src/features/ova-workspace/pages/ova-workspace-page.component.ts
import { Component, inject } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { OvaCreationViewComponent } from "../components/creation/ova-creation-view.component";
import { OvaEditViewComponent } from "../components/editor/ova-edit-view.component";

@Component({
  selector: "gn-ova-workspace-page",
  standalone: true,
  imports: [OvaEditViewComponent, OvaCreationViewComponent],
  template: `
    @if (ovaId) {
      <gn-ova-edit-view [ovaId]="ovaId"></gn-ova-edit-view>
    } @else {
      <gn-ova-creation-view
        [initialJobId]="jobId ?? undefined"
        (onCreated)="handleCreated($event)"
      ></gn-ova-creation-view>
    }
  `,
})
export class OvaWorkspacePageComponent {
  route = inject(ActivatedRoute);
  router = inject(Router);

  get ovaId() {
    return this.route.snapshot.paramMap.get("id");
  }

  get jobId() {
    return this.route.snapshot.queryParamMap.get("jobId");
  }

  handleCreated(id: string) {
    this.router.navigate(["/workspace", id], { replaceUrl: true });
  }
}

// archive/frontend-react-legacy/src/features/ova_workspace/pages/OvaWorkspacePage.tsx
import { useCallback } from 'react'
import { useNavigate, useParams } from 'react-router'
import { OvaCreationView } from '@/features/ova_workspace/components/creation/OvaCreationView'
import { OvaEditView } from '@/features/ova_workspace/components/editor/OvaEditView'

export function OvaWorkspacePage() {
  const { ovaId, jobId } = useParams<{ ovaId?: string; jobId?: string }>()
  const navigate = useNavigate()

  const handleCreated = useCallback(
    (id: string) => navigate(`/ova/${id}/workspace`, { replace: true }),
    [navigate],
  )

  if (ovaId) return <OvaEditView ovaId={ovaId} />

  return <OvaCreationView onCreated={handleCreated} initialJobId={jobId} />
}
