// frontend/src/features/ova-workspace/pages/explore-page.component.ts
import { Component } from "@angular/core";
import { PhasePageComponent } from "../components/phase/phase-page.component";

@Component({
  selector: "gn-explore-page",
  standalone: true,
  imports: [PhasePageComponent],
  template: `
    <gn-phase-page
      phase="EXPLORE"
      emoji="🔍"
      description="Interactúa con simuladores y laboratorios para construir tus propias hipótesis antes de ver la teoría formal."
    ></gn-phase-page>
  `,
})
export class ExplorePageComponent {}

// frontend/src/pages/ExplorePage.jsx
import { PhasePage } from '../components/phase/PhasePage.jsx'
import { fetchExploreRecursos, generateExploreResource } from '../services/exploreService.js'

export function ExplorePage() {
  return (
    <PhasePage
      phase="EXPLORE"
      emoji="🔍"
      description="Interactúa con simuladores y laboratorios para construir tus propias hipótesis antes de ver la teoría formal."
      fetchRecursos={fetchExploreRecursos}
      generateResource={generateExploreResource}
    />
  )
}
