// frontend/src/features/ova-workspace/components/creation/creation-resource-list.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, output } from "@angular/core";

import { IconComponent } from "@/core/components/icon.component";
import { ButtonComponent } from "@/core/components/ui/button.component";

import { groupByPhase, type ResourceVM } from "../../lib/ova-job-view-model";
import { PHASE_ICON_BY_KEY } from "../../lib/resource-icons";

const MARK: Record<string, { icon: string; cls: string }> = {
  X: { icon: "✖", cls: "text-destructive border-destructive/20 bg-destructive/10" },
  generando: { icon: "…", cls: "text-primary border-primary/20 bg-primary/5 animate-pulse" },
  pendiente: { icon: "○", cls: "text-muted-foreground border-border bg-muted" },
};
const CHECK_CLS = "text-primary border-primary/20 bg-primary/10";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-creation-resource-list",
  imports: [CommonModule, ButtonComponent, IconComponent],
  template: `
    <div class="space-y-4">
      @for (g of groups; track g) {
        <div>
          <p class="mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
            <gn-icon [name]="phaseIcon(g.phase)" size="text-xs" /> {{ g.phaseLabel }}
          </p>
          <ul class="space-y-1.5">
            @for (r of g.items; track r) {
              <li class="rounded-lg border border-border bg-background px-3 py-2">
                <div class="flex items-center gap-2.5">
                  @if (r.status === "X") {
                    <input
                      type="checkbox"
                      [checked]="selectedSet.has(r.id)"
                      (change)="onToggle.emit(r.id)"
                      class="shrink-0"
                    />
                  }
                  <span
                    class="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full border text-[13px] font-bold"
                    [ngClass]="markCls(r.status)"
                  >
                    @if (r.status === "check") {
                      <gn-icon name="check" size="text-xs" />
                    } @else {
                      {{ markIcon(r.status) }}
                    }
                  </span>
                  <button
                    type="button"
                    [disabled]="r.status !== 'check'"
                    (click)="r.status === 'check' && onPreview.emit(r.id)"
                    class="flex-1 min-w-0 truncate text-left text-sm"
                    [class.text-foreground]="r.status === 'check'"
                    [class.hover:text-primary]="r.status === 'check'"
                    [class.text-muted-foreground]="r.status !== 'check'"
                    [class.font-semibold]="activeId() === r.id"
                    [class.text-primary]="activeId() === r.id"
                  >
                    {{ r.emoji }} {{ r.label }}
                  </button>
                  @if (r.status === "X") {
                    <gn-button
                      variant="outline"
                      size="sm"
                      (onClick)="onRetry.emit(r.id)"
                      class="shrink-0 text-destructive border-destructive/30"
                    >
                      Reintentar
                    </gn-button>
                  }
                </div>
                @if (r.status === "X") {
                  <p class="mt-1.5 pl-8 text-xs text-destructive">
                    Lo sentimos, hubo un error generando el recurso.
                    @if (r.error_id) {
                      <span class="font-mono"> Error ID: {{ r.error_id }}</span>
                    }
                  </p>
                }
              </li>
            }
          </ul>
        </div>
      }
    </div>
  `,
})
export class CreationResourceListComponent {
  readonly viewModel = input.required<ResourceVM[]>();
  readonly selectedIds = input<string[]>([]);
  readonly activeId = input<string | null>(null);
  readonly onToggle = output<string>();
  readonly onRetry = output<string>();
  readonly onPreview = output<string>();

  get groups() {
    return groupByPhase(this.viewModel());
  }

  get selectedSet() {
    return new Set(this.selectedIds());
  }

  phaseIcon(phase: string) {
    return (PHASE_ICON_BY_KEY[phase] ?? "ph-circle").replace(/^ph-/, "");
  }

  markIcon(status: string) {
    return MARK[status]?.icon || MARK["pendiente"].icon;
  }

  markCls(status: string) {
    if (status === "check") return CHECK_CLS;
    return MARK[status]?.cls || MARK["pendiente"].cls;
  }
}

// frontend/src/features/ova-workspace/components/creation/creation-resource-list.tsx
import { Icon } from "@/core/components/icon";

import { type PhaseGroup } from "../../lib/ova-job-view-model";
import { phaseIconName } from "../../lib/resource-icons";
import { CreationResourceRow } from "./creation-resource-row";

interface Props {
  groups: PhaseGroup[];
  selectedIds: string[];
  activeId: string | null;
  onToggle: (id: string) => void;
  onRetryOne: (id: string) => void;
  onPreview?: (id: string) => void;
}

export function CreationResourceList({ groups, selectedIds, activeId, onToggle, onRetryOne, onPreview }: Readonly<Props>) {
  const selected = new Set(selectedIds);
  return (
    <div className="space-y-4">
      {groups.map((group) => (
        <div key={group.phase}>
          <h3 className="mb-1.5 flex items-center gap-1.5 text-xs font-semibold text-muted-foreground">
            <Icon name={phaseIconName(group.phase)} className="size-3.5" /> {group.phaseLabel}
          </h3>
          <ul className="divide-y divide-border rounded-lg border border-border">
            {group.items.map((resource) => (
              <CreationResourceRow
                key={resource.id}
                resource={resource}
                selected={selected.has(resource.id)}
                active={activeId === resource.id}
                onToggle={() => {
                  onToggle(resource.id);
                }}
                onRetry={() => {
                  onRetryOne(resource.id);
                }}
                onPreview={
                  onPreview
                    ? () => {
                        onPreview(resource.id);
                      }
                    : undefined
                }
              />
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}
