// frontend/src/core/components/html-preview-frame.component.ts
import {
  Component,
  type ElementRef,
  Input,
  inject,
  type OnChanges,
  type OnDestroy,
  type SimpleChanges,
  input,
  viewChild,
} from "@angular/core";
import { DomSanitizer, type SafeResourceUrl } from "@angular/platform-browser";

@Component({
  selector: "gn-html-preview-frame",
  standalone: true,
  imports: [],
  template: `
    <iframe
      #iframe
      [title]="title()"
      [class]="className()"
      [style.height]="height ? height : null"
      sandbox="allow-scripts allow-same-origin"
      [src]="safeUrl"
    ></iframe>
  `,
})
export class HtmlPreviewFrameComponent implements OnChanges, OnDestroy {
  readonly html = input("");
  @Input() height = "60vh";
  readonly className = input("w-full border-0 block");
  readonly title = input("Vista previa del recurso");

  readonly iframeRef = viewChild.required<ElementRef<HTMLIFrameElement>>("iframe");

  private sanitizer = inject(DomSanitizer);

  safeUrl: SafeResourceUrl | null = null;
  private currentBlobUrl: string | null = null;

  ngOnChanges(changes: SimpleChanges) {
    if (changes["html"]) {
      this.updateUrl();
    }
  }

  ngOnDestroy() {
    this.revokeCurrentUrl();
  }

  private updateUrl() {
    this.revokeCurrentUrl();
    const html = this.html();
    if (!html) {
      this.safeUrl = null;
      return;
    }

    const blob = new Blob([html], { type: "text/html" });
    this.currentBlobUrl = URL.createObjectURL(blob);

    this.safeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(this.currentBlobUrl);
  }

  private revokeCurrentUrl() {
    if (this.currentBlobUrl) {
      URL.revokeObjectURL(this.currentBlobUrl);
      this.currentBlobUrl = null;
    }
  }
}

// archive/frontend-react-legacy/src/core/components/HtmlPreviewFrame.tsx
/**
 * Componente base de iframe sandboxed para preview HTML.
 * Gestiona el ciclo de vida del blob URL (crear → revocar en cleanup).
 *
 * Usado por:
 *   - core/components/HtmlCodePreview.tsx
 *   - features/student/components/engage/HtmlPreview.tsx
 *   - features/ova_workspace/components/editor/WorkspaceHtmlPreview.tsx
 */
import { useEffect, useRef } from 'react'

export interface HtmlPreviewFrameProps {
  html: string
  height?: string
  className?: string
  title?: string
}

export function HtmlPreviewFrame({
  html,
  height = '60vh',
  className = 'w-full border-0 block',
  title = 'Vista previa del recurso',
}: HtmlPreviewFrameProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null)

  useEffect(() => {
    if (!html) return
    const url = URL.createObjectURL(new Blob([html], { type: 'text/html' }))
    if (iframeRef.current) iframeRef.current.src = url
    return () => URL.revokeObjectURL(url)
  }, [html])

  return (
    <iframe
      ref={iframeRef}
      title={title}
      className={className}
      style={height ? { height } : undefined}
      sandbox="allow-scripts allow-same-origin"
    />
  )
}
