// frontend/src/core/components/confirm-modal.component.ts
import { ChangeDetectionStrategy, Component, input, output } from "@angular/core";

import { ButtonComponent } from "@/core/components/ui/button.component";
import { DialogComponent } from "@/core/components/ui/dialog.component";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-confirm-modal",
  imports: [DialogComponent, ButtonComponent],
  template: `
    <gn-dialog
      [open]="true"
      width="24rem"
      [disableClose]="isLoading()"
      (openChange)="$event || onCancel.emit()"
    >
      <div class="p-6 bg-card">
        <h2 class="text-lg font-semibold tracking-tight">{{ title() }}</h2>
        <p class="text-sm text-muted-foreground whitespace-pre-line mt-2">
          {{ message() }}
        </p>
        <div class="flex flex-col-reverse sm:flex-row gap-2 sm:gap-3 pt-6">
          <gn-button
            variant="outline"
            class="flex-1"
            (onClick)="onCancel.emit()"
            [disabled]="isLoading()"
          >
            Cancelar
          </gn-button>
          <gn-button
            [variant]="danger() ? 'destructive' : 'default'"
            class="flex-1"
            (onClick)="onConfirm.emit()"
            [disabled]="isLoading()"
            [loading]="isLoading()"
          >
            {{ isLoading() ? "Procesando..." : confirmLabel() }}
          </gn-button>
        </div>
      </div>
    </gn-dialog>
  `,
})
export class ConfirmModalComponent {
  readonly title = input.required<string>();
  readonly message = input.required<string>();
  readonly confirmLabel = input.required<string>();
  readonly isLoading = input(false);
  readonly danger = input(true);

  readonly onConfirm = output();
  readonly onCancel = output();
}

// frontend/src/core/components/confirm-modal.tsx
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogTitle,
} from "@/core/components/ui/alert-dialog";
import { Button } from "@/core/components/ui/button";

interface ConfirmModalProps {
  /** Por defecto `true`: el padre monta/desmonta el modal como en Angular. */
  open?: boolean;
  title: string;
  message: string;
  confirmLabel: string;
  isLoading?: boolean;
  danger?: boolean;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmModal({
  open = true,
  title,
  message,
  confirmLabel,
  isLoading = false,
  danger = true,
  onConfirm,
  onCancel,
}: Readonly<ConfirmModalProps>) {
  // Mientras se procesa no se puede cerrar (Esc incluido): evita dobles envíos a medias.
  const handleOpenChange = (next: boolean) => {
    if (!next && !isLoading) onCancel();
  };

  return (
    <AlertDialog open={open} onOpenChange={handleOpenChange}>
      <AlertDialogContent className="gap-0 bg-card p-6 sm:max-w-sm">
        <AlertDialogTitle className="text-lg font-semibold tracking-tight">
          {title}
        </AlertDialogTitle>
        <AlertDialogDescription className="mt-2 text-sm whitespace-pre-line text-muted-foreground">
          {message}
        </AlertDialogDescription>
        <div className="flex flex-col-reverse gap-2 pt-6 sm:flex-row sm:gap-3">
          <Button
            variant="outline"
            size="lg"
            className="flex-1"
            onClick={onCancel}
            disabled={isLoading}
          >
            Cancelar
          </Button>
          <Button
            variant={danger ? "destructive" : "default"}
            size="lg"
            className="flex-1"
            onClick={onConfirm}
            loading={isLoading}
          >
            {isLoading ? "Procesando..." : confirmLabel}
          </Button>
        </div>
      </AlertDialogContent>
    </AlertDialog>
  );
}
