// frontend/src/core/components/html-preview-frame.component.ts
import {
  Component,
  type ElementRef,
  Input,
  inject,
  type OnChanges,
  type OnDestroy,
  type SimpleChanges,
  input,
  viewChild,
} from "@angular/core";
import { DomSanitizer, type SafeResourceUrl } from "@angular/platform-browser";

@Component({
  selector: "gn-html-preview-frame",
  standalone: true,
  imports: [],
  template: `
    <iframe
      #iframe
      [title]="title()"
      [class]="className()"
      [style.height]="height ? height : null"
      sandbox="allow-scripts allow-same-origin"
      [src]="safeUrl"
    ></iframe>
  `,
})
export class HtmlPreviewFrameComponent implements OnChanges, OnDestroy {
  readonly html = input("");
  @Input() height = "60vh";
  readonly className = input("w-full border-0 block");
  readonly title = input("Vista previa del recurso");

  readonly iframeRef = viewChild.required<ElementRef<HTMLIFrameElement>>("iframe");

  private sanitizer = inject(DomSanitizer);

  safeUrl: SafeResourceUrl | null = null;
  private currentBlobUrl: string | null = null;

  ngOnChanges(changes: SimpleChanges) {
    if (changes["html"]) {
      this.updateUrl();
    }
  }

  ngOnDestroy() {
    this.revokeCurrentUrl();
  }

  private updateUrl() {
    this.revokeCurrentUrl();
    const html = this.html();
    if (!html) {
      this.safeUrl = null;
      return;
    }

    const blob = new Blob([html], { type: "text/html" });
    this.currentBlobUrl = URL.createObjectURL(blob);

    this.safeUrl = this.sanitizer.bypassSecurityTrustResourceUrl(this.currentBlobUrl);
  }

  private revokeCurrentUrl() {
    if (this.currentBlobUrl) {
      URL.revokeObjectURL(this.currentBlobUrl);
      this.currentBlobUrl = null;
    }
  }
}

// frontend/src/core/components/html-preview-frame.tsx
import { useEffect, useRef } from "react";

interface HtmlPreviewFrameProps {
  html?: string;
  /** Altura CSS del iframe; `null` para que la controle `className`. */
  height?: string | null;
  className?: string;
  title?: string;
}

/**
 * Previsualiza HTML generado en un iframe aislado (`sandbox="allow-scripts"`,
 * sin same-origin) a partir de un Blob URL que se revoca al cambiar o desmontar.
 */
export function HtmlPreviewFrame({
  html = "",
  height = "60vh",
  className = "block w-full border-0",
  title = "Vista previa del recurso",
}: Readonly<HtmlPreviewFrameProps>) {
  const frameRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const frame = frameRef.current;
    if (!frame) return undefined;
    if (html === "") {
      frame.src = "about:blank";
      return undefined;
    }
    // charset explícito: sin él los acentos del contenido salen corruptos.
    const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
    frame.src = url;
    return () => {
      URL.revokeObjectURL(url);
    };
  }, [html]);

  return (
    <iframe
      ref={frameRef}
      title={title}
      className={className}
      style={height === null ? undefined : { height }}
      sandbox="allow-scripts"
    />
  );
}
