// frontend/src/features/ova-workspace/components/shared/file-chip.component.ts
import { Component, Input, input, output } from "@angular/core";
import { formatSize } from "../../lib/uploadFormatters";
import type { UploadItem } from "../../lib/uploadTypes";

@Component({
  selector: "gn-file-chip",
  standalone: true,
  imports: [],
  template: `
    <div
      class="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border text-xs font-medium shadow-sm transition duration-200 hover:shadow-md bg-muted text-foreground border-border"
    >
      <span class="text-sm select-none">{{ icon }}</span>
      <div class="flex flex-col min-w-0">
        <span class="max-w-[130px] truncate font-semibold" [title]="file.filename">
          {{ file.filename }}
        </span>
        <span class="text-[9px] opacity-75">
          {{ formattedSize }}
        </span>
      </div>
      <div class="ml-1 flex items-center gap-1">
        @if (file.status === 'uploading') {
          <span class="text-[10px] text-primary animate-pulse font-medium"> Subiendo... </span>
        }

        @if (file.status === 'error') {
          <span class="text-[10px] text-destructive font-semibold" [title]="file.message">
            Error
          </span>
        }

        @if (file.status === 'success' && file.ragStatus) {
          @if (file.ragStatus.status === 'success') {
            <span
              class="text-[10px] text-primary font-bold bg-primary/10 px-1 rounded-sm"
              [title]="'Ingestado en RAG: ' + (file.ragStatus.chunks || 0) + ' fragmentos'"
            >
              RAG ({{ file.ragStatus.chunks || 0 }})
            </span>
          }
          @if (file.ragStatus.status === 'error') {
            <span
              class="text-[10px] text-destructive font-medium"
              [title]="file.ragStatus.message || 'Error RAG'"
            >
              Fallo RAG
            </span>
          }
          @if (file.ragStatus.status !== 'success' && file.ragStatus.status !== 'error') {
            <span class="text-[10px] text-muted-foreground">Listo</span>
          }
        }

        @if (file.status === 'success' && !file.ragStatus) {
          <span class="text-[10px] text-primary font-medium">Listo</span>
        }

        <button
          type="button"
          (click)="onRemove.emit(file.clientId)"
          [disabled]="disabled()"
          class="p-0.5 rounded-full hover:bg-foreground/5 text-current/60 hover:text-current cursor-pointer transition-colors"
          title="Quitar"
        >
          <svg
            aria-hidden="true"
            class="w-3.5 h-3.5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>
    </div>
  `,
})
export class FileChipComponent {
  @Input() file!: UploadItem;
  readonly disabled = input(false);
  readonly onRemove = output<string>();

  get extension() {
    return this.file.filename.split(".").pop()?.toLowerCase() ?? "";
  }

  get icon() {
    const ext = this.extension;
    if (ext === "pdf") return "📕";
    if (["docx", "pptx"].includes(ext)) return "📘";
    if (["mp3", "wav", "m4a", "aac", "ogg", "webm"].includes(ext)) return "🎵";
    if (["jpg", "jpeg", "png", "webp", "gif"].includes(ext)) return "🖼️";
    return "📄";
  }

  get formattedSize() {
    return this.file.sizeBytes ? formatSize(this.file.sizeBytes) : "";
  }
}

// frontend/src/features/ova_workspace/components/shared/FileChip.jsx
import { formatSize } from '@/core/lib/uploads/uploadFormatters'

export function FileChip({ file, onRemove, disabled }) {
  const extension = file.filename.split('.').pop().toLowerCase()
  // El emoji ya distingue el tipo; el chip usa un único estilo on-brand (tokens).
  const colorClass = 'bg-muted text-foreground border-border'
  let icon = '📄'
  if (extension === 'pdf') icon = '📕'
  else if (['docx', 'pptx'].includes(extension)) icon = '📘'
  else if (['mp3', 'wav', 'm4a', 'aac', 'ogg', 'webm'].includes(extension)) icon = '🎵'
  else if (['jpg', 'jpeg', 'png', 'webp', 'gif'].includes(extension)) icon = '🖼️'

  let ragBadge = null
  if (file.status === 'uploading') {
    ragBadge = <span className="text-[10px] text-primary animate-pulse font-medium">Subiendo...</span>
  } else if (file.status === 'error') {
    ragBadge = (
      <span className="text-[10px] text-destructive font-semibold" title={file.message}>
        Error
      </span>
    )
  } else if (file.ragStatus) {
    const status = file.ragStatus.status
    if (status === 'success') {
      const count = file.ragStatus.chunks || 0
      ragBadge = (
        <span
          className="text-[10px] text-primary font-bold bg-primary/10 px-1 rounded-sm"
          title={`Ingestado en RAG: ${count} fragmentos`}
        >
          RAG ({count})
        </span>
      )
    } else if (status === 'error') {
      ragBadge = (
        <span className="text-[10px] text-destructive font-medium" title={file.ragStatus.message || 'Error RAG'}>
          Fallo RAG
        </span>
      )
    } else {
      ragBadge = <span className="text-[10px] text-muted-foreground">Listo</span>
    }
  } else if (file.status === 'success') {
    ragBadge = <span className="text-[10px] text-primary font-medium">Listo</span>
  }

  return (
    <div
      className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border text-xs font-medium shadow-sm transition duration-200 hover:shadow-md ${colorClass}`}
    >
      <span className="text-sm select-none">{icon}</span>
      <div className="flex flex-col min-w-0">
        <span className="max-w-[130px] truncate font-semibold" title={file.filename}>
          {file.filename}
        </span>
        <span className="text-[9px] opacity-75">
          {file.sizeBytes ? formatSize(file.sizeBytes) : ''}
        </span>
      </div>
      <div className="ml-1 flex items-center gap-1">
        {ragBadge}
        <button
          type="button"
          onClick={() => void onRemove(file.clientId)}
          disabled={disabled}
          className="p-0.5 rounded-full hover:bg-foreground/5 text-current/60 hover:text-current cursor-pointer transition-colors"
          title="Quitar"
        >
          <svg aria-hidden="true" className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  )
}
