// frontend/src/features/ova-library/components/cards/ova-card-shell.tsx
import type { ReactNode } from "react";

import { OvaStatusBadge } from "@/core/components/ova-status-badge";
import { Checkbox } from "@/core/components/ui/checkbox";
import { cn } from "@/core/lib/cn";

import type { OvaListItem } from "../../lib/types";
import { OvaCardMeta } from "./ova-card-meta";

interface OvaCardShellProps {
  ova: OvaListItem;
  isSelected?: boolean;
  checkboxDisabled?: boolean;
  dateLabel?: string;
  dateValue?: string;
  dateClassName?: string;
  rootClassName?: string;
  onToggleSelect?: (id: string) => void;
  extraBadges?: ReactNode;
  children?: ReactNode;
}

function formatDateText(label?: string, value?: string): string | null {
  if (!value) return null;
  return label ? `${label} ${value}` : value;
}

/** Contenedor base compartido para tarjetas de OVA en biblioteca y papelera. */
export function OvaCardShell({
  ova,
  isSelected = false,
  checkboxDisabled = false,
  dateLabel,
  dateValue,
  dateClassName = "text-muted-foreground",
  rootClassName,
  onToggleSelect,
  extraBadges,
  children,
}: Readonly<OvaCardShellProps>) {
  const owner = ova.owner as { full_name?: string } | undefined;
  const ownerName = owner?.full_name;
  const dateText = formatDateText(dateLabel, dateValue);
  const borderClass = isSelected ? "border-primary/50 ring-1 ring-primary/20" : "border-border";

  return (
    <div
      className={cn(
        "flex h-full flex-col rounded-xl border bg-card p-5 shadow-sm transition hover:shadow-md",
        borderClass,
        rootClassName,
      )}
    >
      <div className="flex flex-1 items-start gap-3">
        <Checkbox
          className="mt-0.5"
          checked={isSelected}
          onCheckedChange={() => {
            onToggleSelect?.(ova.id);
          }}
          disabled={checkboxDisabled}
          aria-label={`Seleccionar ${ova.title ?? "OVA"}`}
        />
        <div className="min-w-0 flex-1">
          <div className="mb-1 flex flex-wrap items-center gap-2">
            <h3
              className="line-clamp-2 text-sm font-semibold text-foreground"
              title={ova.title ?? ""}
            >
              {ova.title ?? "Sin título"}
            </h3>
            <OvaStatusBadge status={ova.status} />
            {extraBadges}
          </div>
          <OvaCardMeta
            description={ova.description}
            ownerName={ownerName}
            dateText={dateText}
            dateClassName={dateClassName}
          />
        </div>
      </div>
      {children && (
        <div className="mt-4 flex flex-col gap-1.5 border-t border-border pt-3">
          {children}
        </div>
      )}
    </div>
  );
}

// frontend/src/features/ova-library/components/cards/ova-card-shell.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, Input, input, output } from "@angular/core";

import { CheckboxComponent } from "@/core/components/ui/checkbox.component";
import { OvaStatusBadgeComponent } from "@/features/ova-library/components/cards/ova-status-badge.component";
import type { OvaListItem } from "@/features/ova-library/lib/types";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-ova-card-shell",
  imports: [CommonModule, CheckboxComponent, OvaStatusBadgeComponent],
  template: `
    <div [ngClass]="rootClassName() || defaultRootClass">
      <div class="flex flex-1 items-start gap-3">
        <gn-checkbox
          class="mt-0.5"
          [checked]="isSelected()"
          (checkedChange)="onToggleSelect.emit(ova.id)"
          [disabled]="checkboxDisabled()"
          [ariaLabel]="'Seleccionar ' + ova.title"
        ></gn-checkbox>
        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-2 flex-wrap mb-1">
            <h3 class="text-sm font-semibold text-foreground truncate">
              {{ ova.title }}
            </h3>
            <gn-ova-status-badge [status]="ova.status"></gn-ova-status-badge>
            <ng-content select="[extraBadges]"></ng-content>
          </div>
          @if (ova.description) {
            <p class="text-xs text-muted-foreground line-clamp-2 mt-1">
              {{ ova.description }}
            </p>
          }
          @if (ova["owner"]) {
            <p class="mt-1.5 text-xs text-muted-foreground">
              Por: <span class="font-medium text-foreground">{{ getOwnerName() }}</span>
            </p>
          }
          @if (dateValue) {
            <p class="mt-1.5 text-xs" [ngClass]="dateClassName()">
              {{ dateLabel ? dateLabel + " " : "" }}{{ dateValue }}
            </p>
          }
        </div>
      </div>
      <div class="mt-4 flex flex-col gap-1.5 border-t border-border pt-3">
        <ng-content select="[footer]"></ng-content>
      </div>
    </div>
  `,
})
export class OvaCardShellComponent {
  @Input({ required: true }) ova!: OvaListItem;
  readonly isSelected = input(false);
  readonly checkboxDisabled = input(false);
  @Input() dateLabel?: string;
  @Input() dateValue?: string;
  readonly dateClassName = input("text-muted-foreground");
  readonly rootClassName = input<string | undefined>(undefined);

  readonly onToggleSelect = output<string>();

  get defaultRootClass(): string {
    return `flex h-full flex-col rounded-xl border bg-card p-5 shadow-sm hover:shadow-md transition ${
      this.isSelected() ? "border-primary/50 ring-1 ring-primary/20" : "border-border"
    }`;
  }

  getOwnerName(): string {
    const owner = this.ova["owner"] as { full_name?: string } | undefined;
    return owner?.full_name || "";
  }
}
