// frontend/src/features/ova-library/components/cards/trashed-ova-card.component.ts
import { Component, input, output } from "@angular/core";
import { ButtonComponent } from "@/core/components/ui/button.component";
import type { OvaListItem } from "@/features/ova-library/lib/types";
import { OvaCardShellComponent } from "./ova-card-shell.component";

@Component({
  selector: "gn-trashed-ova-card",
  standalone: true,
  imports: [OvaCardShellComponent, ButtonComponent],
  template: `
    <gn-ova-card-shell
      [ova]="ova()"
      [isSelected]="isSelected()"
      (onToggleSelect)="onToggleSelect.emit($event)"
      [rootClassName]="rootClass"
      dateLabel="Eliminado el"
      [dateValue]="formatDate(ova()['deleted_at'])"
      dateClassName="text-red-400 font-medium"
    >
      <div footer class="flex items-center gap-2 w-full">
        <gn-button
          variant="outline"
          size="sm"
          class="flex-1 text-primary border-primary/30 hover:bg-primary/5"
          [disabled]="isRestoring() || isDeleting()"
          (onClick)="onRestore.emit(ova().id)"
        >
          <!-- ↩ -->
          {{ isRestoring() ? 'Restaurando...' : 'Restaurar' }}
        </gn-button>
        <gn-button
          variant="outline"
          size="sm"
          class="flex-1 text-destructive border-destructive/30 hover:bg-destructive/5"
          [disabled]="isRestoring() || isDeleting()"
          (onClick)="onPermanentDelete.emit(ova())"
        >
          <!-- 🗑 -->
          {{ isDeleting() ? 'Eliminando...' : 'Borrar definitivamente' }}
        </gn-button>
      </div>
    </gn-ova-card-shell>
  `,
})
export class TrashedOvaCardComponent {
  readonly ova = input.required<OvaListItem>();
  readonly isSelected = input(false);
  readonly isRestoring = input(false);
  readonly isDeleting = input(false);

  readonly onToggleSelect = output<string>();
  readonly onRestore = output<string>();
  readonly onPermanentDelete = output<OvaListItem>();

  get rootClass(): string {
    return `rounded-xl border bg-white p-5 shadow-sm transition ${
      this.isSelected() ? "border-primary/50 ring-1 ring-primary/20" : "border-border"
    }`;
  }

  formatDate(date: unknown): string {
    if (!date) return "";
    return new Date(date as string).toLocaleDateString();
  }
}

// frontend/src/features/ova-library/components/cards/trashed-ova-card.tsx
import { Button } from "@/core/components/ui/button";

import type { OvaListItem } from "../../lib/types";
import { OvaCardShell } from "./ova-card-shell";

interface TrashedOvaCardProps {
  ova: OvaListItem;
  isSelected?: boolean;
  isRestoring?: boolean;
  isDeleting?: boolean;
  onToggleSelect?: (id: string) => void;
  onRestore?: (id: string) => void;
  onPermanentDelete?: (ova: OvaListItem) => void;
}

function formatDate(date: unknown): string {
  if (!date) return "";
  return new Date(date as string).toLocaleDateString("es-PE");
}

/** Tarjeta de OVA en la papelera con opciones de restaurar o eliminar definitivamente. */
export function TrashedOvaCard({
  ova,
  isSelected = false,
  isRestoring = false,
  isDeleting = false,
  onToggleSelect,
  onRestore,
  onPermanentDelete,
}: Readonly<TrashedOvaCardProps>) {
  return (
    <OvaCardShell
      ova={ova}
      isSelected={isSelected}
      dateLabel="Eliminado el"
      dateValue={formatDate(ova.deleted_at)}
      dateClassName="text-red-400 font-medium"
      onToggleSelect={onToggleSelect}
    >
      <div className="flex w-full items-center gap-2">
        <Button
          variant="outline"
          size="sm"
          className="flex-1 border-primary/30 text-primary hover:bg-primary/5"
          disabled={isRestoring || isDeleting}
          onClick={() => onRestore?.(ova.id)}
        >
          {isRestoring ? "Restaurando..." : "Restaurar"}
        </Button>
        <Button
          variant="outline"
          size="sm"
          className="flex-1 border-destructive/30 text-destructive hover:bg-destructive/5"
          disabled={isRestoring || isDeleting}
          onClick={() => onPermanentDelete?.(ova)}
        >
          {isDeleting ? "Eliminando..." : "Borrar definitivamente"}
        </Button>
      </div>
    </OvaCardShell>
  );
}
