// frontend/src/features/llm-settings/components/model-task-card-chips.tsx
import {
  chipLabel,
  chipModality,
  type ChipModel,
  lookupModalitySymbol,
} from "../lib/model-task-card.helpers";

interface ModelTaskCardChipsProps {
  fallbacks: { provider: string; model_id: string }[];
  models: ChipModel[];
  chip: string;
  num: string;
}

export function ModelTaskCardChips({
  fallbacks,
  models,
  chip,
  num,
}: Readonly<ModelTaskCardChipsProps>) {
  const list = fallbacks;
  if (list.length === 0) {
    return (
      <div className="flex items-center gap-1.5 text-[10px] italic text-muted-foreground">
        <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/20" />
        Sin cadena de respaldo
      </div>
    );
  }

  const visible = list.slice(0, 4);
  const overflow = Math.max(0, list.length - 4);

  return (
    <div className="flex flex-wrap items-center gap-0.5">
      {visible.map((item, index) => (
        <span key={`${item.provider}:${item.model_id}:${String(index)}`} className="inline-flex items-center gap-1">
          {index > 0 ? <span className="text-[8px] font-black text-muted-foreground">→</span> : null}
          <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold ${chip}`}>
            <span className={`text-[9px] ${num}`}>{lookupModalitySymbol(chipModality(item, models))}</span>
            <span className="max-w-[80px] truncate">{chipLabel(item, models)}</span>
          </span>
        </span>
      ))}
      {overflow > 0 ? (
        <span className="inline-flex items-center rounded-full border border-border/50 bg-muted/60 px-2 py-0.5 text-[10px] text-muted-foreground">
          +{overflow}
        </span>
      ) : null}
    </div>
  );
}

// frontend/src/features/llm-settings/components/model-task-card-chips.component.ts
import { CommonModule } from "@angular/common";
import { Component, input } from "@angular/core";
import {
  chipLabel,
  chipModality,
  lookupModalitySymbol,
  type ChipModel,
} from "../lib/model-task-card.helpers";

@Component({
  selector: "gn-model-task-card-chips",
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (!fallbacks()?.length) {
      <div class="flex items-center gap-1.5 text-[10px] italic text-muted-foreground/40">
        <span class="h-1.5 w-1.5 rounded-full bg-muted-foreground/20"></span>
        Sin cadena de respaldo
      </div>
    } @else {
      <div class="flex flex-wrap items-center gap-0.5">
        @for (f of visible; track $index; let i = $index) {
          <span class="inline-flex items-center gap-1">
            @if (i > 0) {
              <span class="text-[8px] text-muted-foreground/30 font-black">→</span>
            }
            <span
              class="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold border"
              [ngClass]="chip()"
            >
              <span class="text-[9px]" [ngClass]="num()">
                {{ modalitySymbol(f) }}
              </span>
              <span class="truncate max-w-[80px]">{{ label(f) }}</span>
            </span>
          </span>
        }
        @if (overflow > 0) {
          <span
            class="inline-flex items-center rounded-full bg-muted/60 px-2 py-0.5 text-[10px] text-muted-foreground border border-border/50"
          >
            +{{ overflow }}
          </span>
        }
      </div>
    }
  `,
})
export class ModelTaskCardChipsComponent {
  readonly fallbacks =
    input.required<
      Array<{
        provider: string;
        model_id: string;
      }>
    >();
  readonly models = input.required<ChipModel[]>();
  readonly chip = input.required<string>();
  readonly num = input.required<string>();

  get visible() {
    return (this.fallbacks() ?? []).slice(0, 4);
  }

  get overflow() {
    return Math.max(0, (this.fallbacks()?.length ?? 0) - 4);
  }

  label(f: { provider: string; model_id: string }) {
    return chipLabel(f, this.models());
  }

  modalitySymbol(f: { provider: string; model_id: string }) {
    return lookupModalitySymbol(chipModality(f, this.models()));
  }
}
