// frontend/src/features/llm-settings/components/user-key-row.tsx
import { useRef, useState } from "react";

import { providerMeta } from "@/core/components/platform-key-meta";
import { cn } from "@/core/lib/cn";

import { errorMessage } from "../hooks/error-message";
import { useUserApiKeys } from "../hooks/use-user-api-keys";
import { UserKeyRowActions } from "./user-key-row-actions";
import { UserKeyRowHeader } from "./user-key-row-header";

interface UserKeyRowProps {
  provider: string;
  maskedValue?: string;
}

export function UserKeyRow({ provider, maskedValue }: Readonly<UserKeyRowProps>) {
  const { save } = useUserApiKeys();
  const inputRef = useRef<HTMLInputElement>(null);
  const state = useKeyDraft();
  const placeholder = providerMeta(provider).placeholder;

  return (
    <div className="space-y-3 rounded-xl border border-border bg-background p-4 shadow-sm">
      <UserKeyRowHeader provider={provider} configured={Boolean(maskedValue)} />
      <div className="flex flex-col gap-2 sm:flex-row">
        <input
          ref={inputRef}
          type="password"
          value={state.editing ? state.draft : (maskedValue ?? "")}
          readOnly={!state.editing}
          placeholder={placeholder}
          onChange={(event) => {
            state.setDraft(event.target.value);
          }}
          className={cn(
            "flex-1 rounded-lg border border-border px-3 py-2 font-mono text-xs",
            state.editing ? "bg-background" : "bg-muted/30 text-muted-foreground",
          )}
        />
        <UserKeyRowActions
          editing={state.editing}
          configured={Boolean(maskedValue)}
          saving={state.saving}
          canSave={state.draft.trim().length > 0}
          onStart={() => {
            state.start();
            window.setTimeout(() => inputRef.current?.focus(), 50);
          }}
          onCancel={state.cancel}
          onSave={() => {
            void state.persist(provider, save);
          }}
        />
      </div>
      {state.rowError ? <p className="text-xs text-destructive">{state.rowError}</p> : null}
    </div>
  );
}

function useKeyDraft() {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const [saving, setSaving] = useState(false);
  const [rowError, setRowError] = useState<string | null>(null);

  return {
    editing,
    draft,
    saving,
    rowError,
    setDraft,
    start: () => {
      setDraft("");
      setEditing(true);
      setRowError(null);
    },
    cancel: () => {
      setEditing(false);
      setDraft("");
    },
    persist: async (provider: string, save: ReturnType<typeof useUserApiKeys>["save"]) => {
      setSaving(true);
      setRowError(null);
      try {
        await save({ provider, key: draft.trim() });
        setEditing(false);
        setDraft("");
      } catch (err: unknown) {
        setRowError(errorMessage(err, "Error al guardar."));
      } finally {
        setSaving(false);
      }
    },
  };
}

// frontend/src/features/llm-settings/components/user-key-row.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  type ElementRef,
  inject,
  Input,
  input,
  output,
  viewChild,
} from "@angular/core";
import { FormsModule } from "@angular/forms";

import { PROVIDER_META } from "@/core/components/platform-key-meta";

import { UserLlmSettingsService } from "../services/user-llm-settings.service";

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: "gn-user-key-row",
  imports: [CommonModule, FormsModule],
  template: `
    <div class="rounded-xl border border-border bg-background p-4 space-y-3 shadow-sm">
      <div class="flex items-start justify-between gap-3">
        <div>
          <p class="font-semibold text-sm">{{ meta.label }}</p>
          <p class="text-xs text-muted-foreground mt-0.5">{{ meta.desc }}</p>
        </div>
        <span
          class="shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase border"
          [ngClass]="
            isConfigured
              ? 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20'
              : 'bg-muted text-muted-foreground'
          "
        >
          {{ isConfigured ? "Conectado" : "Sin configurar" }}
        </span>
      </div>
      <div class="flex flex-col sm:flex-row gap-2">
        <input
          #inputEl
          [type]="show ? 'text' : 'password'"
          [(ngModel)]="value"
          [placeholder]="meta.placeholder"
          [readonly]="!editing"
          class="flex-1 rounded-lg border border-border px-3 py-2 text-xs font-mono"
          [ngClass]="editing ? 'bg-background' : 'bg-muted/30 text-muted-foreground'"
        />
        <div class="flex gap-2">
          @if (editing) {
            <button
              type="button"
              (click)="handleSave()"
              [disabled]="saving || !value.trim()"
              class="h-9 px-3 rounded-md bg-primary text-primary-foreground text-xs font-bold disabled:opacity-50"
            >
              {{ saving ? "..." : "Guardar" }}
            </button>
            <button type="button" (click)="cancelEdit()" class="h-9 px-3 rounded-md border text-xs">
              Cancelar
            </button>
          } @else {
            <button
              type="button"
              (click)="startEdit()"
              class="h-9 px-3 rounded-md text-xs font-bold"
              [ngClass]="isConfigured ? 'border' : 'bg-primary text-primary-foreground'"
            >
              {{ isConfigured ? "Cambiar" : "Configurar" }}
            </button>
          }
        </div>
      </div>
      @if (rowError) {
        <p class="text-xs text-destructive">{{ rowError }}</p>
      }
    </div>
  `,
})
export class UserKeyRowComponent {
  readonly provider = input.required<string>();
  @Input() set maskedValue(val: string | undefined) {
    this._maskedValue = val;
    if (!this.editing) this.value = val || "";
  }
  get maskedValue() {
    return this._maskedValue;
  }
  private _maskedValue?: string;

  readonly onSaved = output<Record<string, string>>();

  readonly inputEl = viewChild.required<ElementRef<HTMLInputElement>>("inputEl");

  private service = inject(UserLlmSettingsService);

  editing = false;
  value = "";
  show = false;
  saving = false;
  rowError: string | null = null;

  get meta() {
    return (
      PROVIDER_META[this.provider()] ?? {
        label: this.provider(),
        placeholder: "...",
        desc: "Proveedor",
        compat: false,
      }
    );
  }

  get isConfigured(): boolean {
    return !!this.maskedValue;
  }

  startEdit() {
    this.value = "";
    this.editing = true;
    this.rowError = null;
    setTimeout(() => {
      this.inputEl()?.nativeElement?.focus();
    }, 50);
  }

  cancelEdit() {
    this.editing = false;
    this.value = this.maskedValue || "";
  }

  async handleSave() {
    this.saving = true;
    this.rowError = null;
    try {
      const result = await this.service.saveApiKey(this.provider(), this.value.trim());
      this.onSaved.emit(result.api_keys);
      this.editing = false;
      this.value = result.api_keys[this.provider()] || "";
    } catch (e: unknown) {
      this.rowError = e instanceof Error ? e.message : "Error al guardar.";
    } finally {
      this.saving = false;
    }
  }
}
