// frontend/src/features/analytics/pages/analytics-page.component.ts
import { Component, inject, type OnInit } from "@angular/core";
import { Router } from "@angular/router";
import {
  StatCardsComponent,
  StatusBreakdownComponent,
} from "../components/analytics-cards.component";
import { RecentOvasComponent, TopCreatorsComponent } from "../components/analytics-lists.component";
import type { AnalyticsData } from "../lib/types";
import { AnalyticsService } from "../services/analytics.service";

@Component({
  selector: "gn-analytics-page",
  standalone: true,
  imports: [
    StatCardsComponent,
    StatusBreakdownComponent,
    TopCreatorsComponent,
    RecentOvasComponent,
  ],
  template: `
    <div class="mx-auto max-w-4xl space-y-6 pb-12 animate-in fade-in duration-300">
      <header class="space-y-1">
        <h1 class="font-display text-2xl font-bold">Analítica de aprendizaje</h1>
        <p class="text-sm text-muted-foreground">
          {{ isLoading ? 'Cargando métricas…' : 'Métricas de ' + scopeLabel + '.' }}
        </p>
      </header>

      @if (isLoading) {
        <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
          @for (i of [0, 1, 2]; track i) {
            <div class="h-24 animate-pulse rounded-2xl bg-muted/50"></div>
          }
        </div>
      }

      @if (!isLoading && error) {
        <div
          class="rounded-2xl border border-destructive/40 bg-destructive/5 p-5 text-sm text-destructive"
        >
          No se pudieron cargar las analíticas. Intenta de nuevo más tarde.
        </div>
      }

      @if (!isLoading && !error && data) {
        <gn-stat-cards [totals]="data.totals" [scope]="data.scope"></gn-stat-cards>
        <div class="grid gap-4 md:grid-cols-2">
          <gn-status-breakdown [byStatus]="data.ova_by_status"></gn-status-breakdown>
          <gn-top-creators [creators]="data.top_creators"></gn-top-creators>
        </div>
        <gn-recent-ovas [ovas]="data.recent_ovas"></gn-recent-ovas>
      }
    </div>
  `,
})
export class AnalyticsPageComponent implements OnInit {
  data: AnalyticsData | null = null;
  isLoading = true;
  error: any = null;

  private analyticsService = inject(AnalyticsService);
  private router = inject(Router);

  get scopeLabel() {
    return this.data?.scope === "platform" ? "toda la plataforma" : "tus alumnos vinculados";
  }

  async ngOnInit() {
    try {
      this.data = await this.analyticsService.getAnalytics();
    } catch (err: any) {
      if (err.code === "forbidden") {
        this.router.navigate(["/dashboard"], { replaceUrl: true });
        return;
      }
      this.error = err;
    } finally {
      this.isLoading = false;
    }
  }
}

// frontend/src/features/analytics/pages/AnalyticsPage.tsx
import { m as motion } from 'motion/react'
import { Navigate } from 'react-router'
import { useAnalytics } from '@/features/analytics/hooks/useAnalytics'
import { StatCards, StatusBreakdown } from '@/features/analytics/components/AnalyticsCards'
import { RecentOvas, TopCreators } from '@/features/analytics/components/AnalyticsLists'

function LoadingState() {
  return (
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
      {[0, 1, 2].map((i) => (
        <div key={i} className="h-24 animate-pulse rounded-2xl bg-muted/50" />
      ))}
    </div>
  )
}

export function AnalyticsPage() {
  const { data, isLoading, error } = useAnalytics()

  // Sin permiso: el backend devuelve 403 → redirige al dashboard.
  if ((error as { code?: string } | null)?.code === 'forbidden') {
    return <Navigate to="/dashboard" replace />
  }

  const scopeLabel = data?.scope === 'platform' ? 'toda la plataforma' : 'tus alumnos vinculados'

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.25 }}
      className="mx-auto max-w-4xl space-y-6 pb-12"
    >
      <header className="space-y-1">
        <h1 className="font-display text-2xl font-bold">Analítica de aprendizaje</h1>
        <p className="text-sm text-muted-foreground">
          {isLoading ? 'Cargando métricas…' : `Métricas de ${scopeLabel}.`}
        </p>
      </header>

      {isLoading ? (
        <LoadingState />
      ) : error ? (
        <div className="rounded-2xl border border-destructive/40 bg-destructive/5 p-5 text-sm text-destructive">
          No se pudieron cargar las analíticas. Intenta de nuevo más tarde.
        </div>
      ) : data ? (
        <>
          <StatCards totals={data.totals} scope={data.scope} />
          <div className="grid gap-4 md:grid-cols-2">
            <StatusBreakdown byStatus={data.ova_by_status} />
            <TopCreators creators={data.top_creators} />
          </div>
          <RecentOvas ovas={data.recent_ovas} />
        </>
      ) : null}
    </motion.div>
  )
}
